(()=>{
'use strict';
const $=id=>document.getElementById(id);
const WEEKS=window.BTM_WEEKS||[];
const PROGRAM=window.BTM_TRAINING_WEEKS||{};
let week=1,state={};
try{state=JSON.parse(localStorage.getItem('btm_progress')||'{}')}catch{state={}}
const quotes={NOVICE:'Every expert was once willing to begin.',BEGINNER:'Small steps become serious progress when you refuse to stop.',TRAINEE:'Consistency turns effort into ability.',APPRENTICE:'Skill grows when discipline becomes routine.',SKILLED:'You are no longer learning the work, you are becoming the work.',ADVANCED:'Discipline begins where excuses lose their power.',RECOVERY:'Recovery is not retreat, it is how strength prepares to rise again.',ELITE:'You earned your place by doing what most people abandon.',EXPERT:'Control your effort, sharpen your execution, raise your standard.',MASTER:'Mastery is built through consistency when motivation disappears.',GRANDMASTER:'At this level, discipline is no longer an action, it is an identity.',LEGEND:'The final level is not the end, it is proof of what you became.'};
const block=w=>w<=4?'FOUNDATION BLOCK':w<=6?'DIFFICULTY BLOCK':w===7?'DELOAD BLOCK':w<=9?'REBUILD BLOCK':w===10?'VARIATION BLOCK':'PEAK BLOCK';
const key=(d,i)=>week+'|'+d+'|'+i;
function item(d,i){const k=key(d,i);if(!state[k])state[k]={done:false,feel:'',sets:[]};return state[k]}
function save(){localStorage.setItem('btm_progress',JSON.stringify(state));updateStats();draw()}
function current(){return PROGRAM[week]}
function renderWeeks(){const root=$('weekGrid');if(!root)return;root.replaceChildren();for(const w of WEEKS){const b=document.createElement('button');b.type='button';b.className='week'+(week===w.id?' active':'');b.style.setProperty('--week-color',w.color);if(w.isDeload)b.classList.add('deload');const n=document.createElement('b'),r=document.createElement('span');n.textContent='WEEK '+w.id;r.textContent=w.rank+(w.isDeload?' · DELOAD':'');b.append(n,r);b.onclick=()=>{week=w.id;renderWeeks();renderRank();renderWorkouts()};root.appendChild(b)}const reset=$('resetWeekBtn');if(reset)reset.textContent='ERASE WEEK '+week}
function renderRank(){const meta=WEEKS[week-1]||{},p=$('rankPanel');if(!p)return;p.style.setProperty('--rank-color',meta.color||'#66b9df');$('rankKicker').textContent='ACHIEVEMENT RANK · WEEK '+week+(meta.isDeload?' · DELOAD':'');$('rankName').textContent=meta.rank||'WEEK '+week;$('rankQuote').textContent=quotes[meta.rank]||''}
function prescription(e){return `${e.sets} × ${e.reps} · ${e.rir} RIR`}
function renderWorkouts(){const root=$('workouts');if(!root)return;root.replaceChildren();const meta=WEEKS[week-1]||{},program=current();if(!program)return;
const banner=document.createElement('div');banner.className='panel banner'+(program.deload?' deload-banner':'');
const ey=document.createElement('div'),title=document.createElement('h2'),note=document.createElement('p');ey.className='ey';ey.textContent='WEEK '+week+' · '+(meta.rank||'PROGRAM');title.textContent=program.deload?'RECOVERY · DELOAD':block(week);note.className='note';note.textContent=program.deload?'Training stress is deliberately reduced: fewer sets, easier variations and 4 RIR. Recover now so Weeks 8–12 can progress again.':'Complete the fixed prescription with clean form. RIR controls effort, while the Week configuration controls progression. Completion never rewrites future Weeks.';banner.append(ey,title,note);root.appendChild(banner);
program.days.forEach((day,di)=>{const box=document.createElement('div');box.className='day';const head=document.createElement('div');head.className='day-head';const strong=document.createElement('strong'),count=document.createElement('span');strong.textContent=day.day;const done=day.exercises.reduce((n,_,i)=>n+(item(di,i).done?1:0),0);count.textContent=done+'/'+day.exercises.length+' complete';head.append(strong,count);box.appendChild(head);
 day.exercises.forEach((e,i)=>{const x=item(di,i),el=document.createElement('div');el.className='exercise'+(x.done?' done':'');if(program.deload)el.classList.add('deload');
 const top=document.createElement('div');top.className='top';const info=document.createElement('div'),name=document.createElement('div'),target=document.createElement('div'),variation=document.createElement('div'),check=document.createElement('input');name.className='name';name.textContent=e.name;target.className='target';target.textContent=prescription(e);variation.className='target';variation.textContent=e.variation===e.name?'':e.variation;variation.style.marginTop='2px';variation.style.fontSize='9px';variation.style.opacity='.8';check.className='check';check.type='checkbox';check.checked=!!x.done;info.append(name,target);if(e.variation!==e.name)info.append(variation);top.append(info,check);
 const sets=document.createElement('div');sets.className='sets';const previous=x.sets||[];x.sets=Array.from({length:e.sets},(_,j)=>previous[j]||'');x.sets.forEach((v,j)=>{const inp=document.createElement('input');inp.value=v;inp.placeholder='Set '+(j+1);inp.oninput=()=>{x.sets[j]=inp.value;save()};sets.appendChild(inp)});
 const feel=document.createElement('div');feel.className='feel';['clean','mediocre','bad'].forEach(f=>{const b=document.createElement('button');b.type='button';b.textContent=f;b.className=x.feel===f?'active':'';b.onclick=()=>{x.feel=f;save();renderWorkouts()};feel.appendChild(b)});
 const bar=document.createElement('div');bar.className='bar';const fill=document.createElement('i');fill.style.width=x.done?'100%':'0%';bar.appendChild(fill);el.append(top,sets,feel,bar);check.onchange=e2=>{x.done=e2.target.checked;save();renderWorkouts()};box.appendChild(el)});root.appendChild(box)})}
function updateStats(){let ex=0,clean=0,score=0,sessions=new Set(),weeksDone=new Set();for(const[k,x]of Object.entries(state)){if(!x.done)continue;const[w,d]=k.split('|');ex++;weeksDone.add(w);sessions.add(w+'|'+d);if(x.feel==='clean'){clean++;score+=3}else if(x.feel==='mediocre')score+=2;else if(x.feel==='bad')score++}$('exCount').textContent=ex;$('cleanRate').textContent=ex?Math.round(clean/ex*100)+'%':'0%';$('sessionCount').textContent=sessions.size;$('weekCount').textContent=weeksDone.size+'/12';$('score').textContent=score}
function draw(){const c=$('chart');if(!c)return;const ctx=c.getContext('2d'),w=c.clientWidth||800,h=220,d=window.devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const vals=WEEKS.map(wi=>{let n=0;const p=PROGRAM[wi.id];p?.days.forEach((day,di)=>day.exercises.forEach((_,i)=>{const x=state[wi.id+'|'+di+'|'+i];if(x?.done)n+=x.feel==='clean'?3:x.feel==='mediocre'?2:x.feel==='bad'?1:0}));return n}),max=Math.max(1,...vals),left=35,right=10,top=15,bottom=25,pw=w-left-right,ph=h-top-bottom;ctx.strokeStyle='#294252';for(let i=0;i<4;i++){const y=top+ph*i/3;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(w-right,y);ctx.stroke()}ctx.strokeStyle='#66b9df';ctx.lineWidth=2;ctx.beginPath();vals.forEach((v,i)=>{const x=left+i*pw/11,y=top+ph-v/max*ph;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#66b9df';vals.forEach((v,i)=>{const x=left+i*pw/11,y=top+ph-v/max*ph;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill()})}
$('resetWeekBtn')?.addEventListener('click',()=>{if(confirm('Erase ALL training progression logs for Week '+week+'? This cannot be undone.')){Object.keys(state).filter(k=>k.startsWith(week+'|')).forEach(k=>delete state[k]);save();renderWeeks();renderRank();renderWorkouts()}});
renderWeeks();renderRank();renderWorkouts();updateStats();draw();window.addEventListener('resize',draw);
})();
