/* Character logo system, rebuilt from the 12 user-provided logo references. */
(()=> {
'use strict';
if(window.__BTM_CHARACTER_LOGOS__) return;
window.__BTM_CHARACTER_LOGOS__=1;
const WEEK_COLORS=['#66b9df','#e86a78','#b58cff','#7ec8a0','#d6a45d','#d6c36a','#8c82d8','#e58b5b','#6fb8d6','#a879d6','#c98b58','#d05b68'];
const LOGO_NAMES=['Week 1 Character Emblem','Week 2 Character Emblem','Week 3 Character Emblem','Week 4 Character Emblem','Week 5 Character Emblem','Week 6 Character Emblem','Week 7 Character Emblem','Week 8 Character Emblem','Week 9 Character Emblem','Week 10 Character Emblem','Week 11 Character Emblem','Week 12 Character Emblem'];
const LOGOS=[`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`,`<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><g fill="currentColor" fill-rule="evenodd"><path d="M 0.0,0.0 L 100.0,0.0 L 100.0,100.0 L 0.0,100.0 Z"/></g></svg>`].map((svg,i)=>({week:i+1,svg,name:LOGO_NAMES[i],color:WEEK_COLORS[i]}));
const css=`.btm-character-card{--emblem-color:#66b9df}.btm-character-copy{position:relative;display:flex;flex-direction:column;justify-content:center;min-width:0}.btm-inline-emblem{position:absolute;right:18px;top:50%;width:58px;height:58px;transform:translateY(-50%);color:var(--emblem-color);opacity:.92;pointer-events:none;filter:drop-shadow(0 0 10px color-mix(in srgb,var(--emblem-color) 30%,transparent));transition:opacity .25s ease,filter .25s ease,transform .25s ease}.btm-inline-emblem svg,.btm-emblem svg,.btm-week-emblem svg{width:100%;height:100%;display:block}.btm-character-card .btm-emblem-panel{--emblem-color:#66b9df;position:relative;display:flex;align-items:center;justify-content:center;min-height:150px;border:1px solid color-mix(in srgb,var(--emblem-color) 42%,#294656);border-radius:8px;background:radial-gradient(circle at 50% 38%,color-mix(in srgb,var(--emblem-color) 18%,transparent),transparent 58%),#09141b;overflow:hidden}.btm-character-card .btm-emblem-panel:before{content:'';position:absolute;inset:10px;border:1px solid color-mix(in srgb,var(--emblem-color) 18%,transparent);border-radius:6px;pointer-events:none}.btm-emblem{width:104px;height:104px;display:grid;place-items:center;color:var(--emblem-color);filter:drop-shadow(0 0 14px color-mix(in srgb,var(--emblem-color) 32%,transparent));transition:transform .28s ease,filter .28s ease,opacity .28s ease;animation:btmLogoIn .34s ease both}.btm-emblem-label{position:absolute;left:14px;bottom:11px;font:8px 'JetBrains Mono';letter-spacing:.16em;text-transform:uppercase;color:color-mix(in srgb,var(--emblem-color) 70%,#8195a3)}.btm-emblem-panel:hover .btm-emblem{transform:translateY(-3px) scale(1.035);filter:drop-shadow(0 0 20px color-mix(in srgb,var(--emblem-color) 52%,transparent))}.btm-week-emblem{position:absolute;right:10px;top:50%;width:42px;height:42px;transform:translateY(-50%);display:grid;place-items:center;color:var(--emblem-color,#66b9df);opacity:.78;transition:transform .25s ease,opacity .25s ease,filter .25s ease}.btm-week-emblem svg{filter:drop-shadow(0 0 7px color-mix(in srgb,var(--emblem-color,#66b9df) 30%,transparent))}.week{position:relative;padding-right:60px}.week:hover .btm-week-emblem,.week.active .btm-week-emblem{opacity:1;transform:translateY(-50%) scale(1.08);filter:drop-shadow(0 0 12px color-mix(in srgb,var(--emblem-color,#66b9df) 48%,transparent))}@keyframes btmLogoIn{from{opacity:0;transform:translateY(6px) scale(.92)}to{opacity:1;transform:none}}@media(max-width:700px){.btm-inline-emblem{width:44px;height:44px;right:10px}.btm-emblem{width:82px;height:82px}.btm-week-emblem{width:34px;height:34px;right:8px}.week{padding-right:50px}}@media(prefers-reduced-motion:reduce){.btm-emblem,.btm-week-emblem,.btm-inline-emblem{transition:none!important;animation:none!important}}`;
if(!document.getElementById('btm-character-emblem-style')){const style=document.createElement('style');style.id='btm-character-emblem-style';style.textContent=css;document.head.appendChild(style)}
function logo(i){return LOGOS[Math.max(0,Math.min(11,i))]}
function setColor(el,i){if(el)el.style.setProperty('--emblem-color',WEEK_COLORS[i]||WEEK_COLORS[0])}
function activeIndex(grid){if(!grid)return 0;const i=[...grid.querySelectorAll('.week')].findIndex(b=>b.classList.contains('active'));return i<0?0:i}
function setSvg(el,i,cls){const l=logo(i);if(!el)return;el.className=cls;el.innerHTML=l.svg;el.dataset.week=String(l.week);el.setAttribute('aria-label',l.name);setColor(el,i)}
function decorateWeeks(grid){if(!grid)return;grid.querySelectorAll('.week').forEach((b,i)=>{setColor(b,i);let icon=b.querySelector('.btm-week-emblem');if(!icon){icon=document.createElement('span');icon.className='btm-week-emblem';b.appendChild(icon)}setSvg(icon,i,'btm-week-emblem')})}
function updateCard(){const card=document.getElementById('btm-character-card'),grid=document.getElementById('weekGrid');if(!card||!grid)return;const i=activeIndex(grid);decorateWeeks(grid);const inline=card.querySelector('.btm-inline-emblem');if(inline)setSvg(inline,i,'btm-inline-emblem');const panel=card.querySelector('#btm-selected-emblem-panel');if(panel){setColor(panel,i);const em=panel.querySelector('.btm-emblem');if(em)setSvg(em,i,'btm-emblem');let label=panel.querySelector('.btm-emblem-label');if(!label){label=document.createElement('span');label.className='btm-emblem-label';panel.appendChild(label)}label.textContent=logo(i).name}}
function patchCard(){const card=document.getElementById('btm-character-card'),grid=document.getElementById('weekGrid');if(!card||!grid)return false;const wrap=card.querySelector('.btm-silhouette-wrap');if(wrap){const copy=card.firstElementChild;if(copy){copy.classList.add('btm-character-copy');if(!copy.querySelector('.btm-inline-emblem')){const inline=document.createElement('span');setSvg(inline,activeIndex(grid),'btm-inline-emblem');copy.appendChild(inline)}}const panel=document.createElement('div');panel.className='btm-emblem-panel';panel.id='btm-selected-emblem-panel';const em=document.createElement('span');setSvg(em,activeIndex(grid),'btm-emblem');panel.appendChild(em);const label=document.createElement('span');label.className='btm-emblem-label';label.textContent=logo(activeIndex(grid)).name;panel.appendChild(label);setColor(panel,activeIndex(grid));wrap.replaceWith(panel)}updateCard();return true}
function bindGrid(){const grid=document.getElementById('weekGrid');if(!grid||grid.__btmLogoBound)return;grid.__btmLogoBound=true;grid.addEventListener('click',()=>requestAnimationFrame(updateCard),{passive:true})}
function boot(){patchCard();bindGrid();requestAnimationFrame(()=>{patchCard();bindGrid()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();