/* Unified UI bootstrap, performance-safe. */
(()=>{
  if(window.__btmShellBootstrapLoaded)return;
  window.__btmShellBootstrapLoaded=true;
  const syncTraining=()=>{const training=document.getElementById('trainingView');if(training)training.style.display=document.body.dataset.section==='training'?'block':'none'};
  const installCss=(id,href)=>{if(document.getElementById(id))return;const link=document.createElement('link');link.id=id;link.rel='stylesheet';link.href=href;document.head.appendChild(link)};
  const installWeekPolish=()=>{if(document.getElementById('btm-week-polish-style'))return;const style=document.createElement('style');style.id='btm-week-polish-style';style.textContent=`#weekGrid .week:nth-child(1){--week-color:#66b9df}#weekGrid .week:nth-child(2){--week-color:#74c7b8}#weekGrid .week:nth-child(3){--week-color:#8ccf70}#weekGrid .week:nth-child(4){--week-color:#b9d45d}#weekGrid .week:nth-child(5){--week-color:#d7bd58}#weekGrid .week:nth-child(6){--week-color:#e09b55}#weekGrid .week:nth-child(7){--week-color:#8d9aa4}#weekGrid .week:nth-child(8){--week-color:#d37a63}#weekGrid .week:nth-child(9){--week-color:#c96879}#weekGrid .week:nth-child(10){--week-color:#a76dc4}#weekGrid .week:nth-child(11){--week-color:#7588d1}#weekGrid .week:nth-child(12){--week-color:#66b9df}#weekGrid .week.active{border-color:var(--week-color)!important;box-shadow:0 0 14px color-mix(in srgb,var(--week-color) 12%,transparent)}`;document.head.appendChild(style);const grid=document.getElementById('weekGrid');if(!grid)return;const difficulties=['Foundation','Foundation+','Build','Build+','Hard','Hard+','Deload','Rebuild','Hard','Hard+','Peak','Machine'];const apply=()=>[...grid.querySelectorAll('.week')].forEach((b,i)=>{const s=b.querySelector('small');if(s&&!s.dataset.difficulty){s.textContent+=' · '+difficulties[i];s.dataset.difficulty='1'}});apply();new MutationObserver(apply).observe(grid,{childList:true,subtree:true})};
  const loadScript=(src,onload)=>{if(document.querySelector(`script[data-btm-src="${src}"]`)){if(onload)onload();return}const s=document.createElement('script');s.src=src;s.defer=true;s.dataset.btmSrc=src;if(onload)s.onload=onload;document.head.appendChild(s)};
  const load=()=>{installCss('btm-polish-link','./polish.css');installCss('btm-water-link','./water-motion.css');loadScript('./app-shell.js',()=>{syncTraining();installWeekPolish();if(!window.__btmSectionObserver){window.__btmSectionObserver=true;new MutationObserver(syncTraining).observe(document.body,{attributes:true,attributeFilter:['data-section']})}loadScript('./running-polish.js');loadScript('./week-pixels.js');loadScript('./app-performance-fix.js',()=>loadScript('./food-calculator-v2.js'))})};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
