/* Universal reset controller, intentionally event-driven and observer-free. */
(()=>{
'use strict';
if(window.__BTM_UNIVERSAL_RESET__)return;
window.__BTM_UNIVERSAL_RESET__=1;
const START=new Date('2026-08-10T00:00:00');
const pad=n=>String(n).padStart(2,'0');
const dateFor=(w,d)=>{const x=new Date(START);x.setDate(x.getDate()+(w-1)*7+d);return x};
const dateKey=(w,d)=>{const x=dateFor(w,d);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`};
const read=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const $=s=>document.querySelector(s);
const all=s=>[...document.querySelectorAll(s)];
const section=()=>document.body.dataset.section||'training';
const activeWeek=grid=>{const b=$(grid+' .week.active');if(!b)return 1;const m=(b.textContent||'').match(/WEEK\s+(\d+)/i);return m?Number(m[1]):1};
const activeDay=grid=>{const bs=all(grid+' .day'),i=bs.findIndex(b=>b.classList.contains('active'));return i<0?0:i};
function selection(){const s=section();if(s==='food'){const w=activeWeek('#foodWeeks'),d=activeDay('#foodDays');return{type:'day',section:s,week:w,day:d}}if(s==='running'){const w=activeWeek('#runWeeks'),d=activeDay('#runDays');return{type:'day',section:s,week:w,day:d}}if(s==='sleep'){const w=activeWeek('#sleepWeeks'),d=activeDay('#sleepDays');return{type:'day',section:s,week:w,day:d}}return{type:'week',section:'training',week:activeWeek('#weekGrid')};}
const css=`
#btm-universal-reset{margin-left:auto;display:inline-flex;align-items:center;justify-content:center;min-width:112px;height:30px;padding:0 13px;border:1px solid rgba(181,92,99,.48);border-radius:5px;background:linear-gradient(145deg,rgba(48,25,29,.72),rgba(29,17,21,.72));color:#c99da1;font:10px 'JetBrains Mono';font-weight:700;letter-spacing:.05em;cursor:pointer;transition:transform .2s ease,border-color .2s ease,box-shadow .25s ease,color .2s ease,background .2s ease}.btm-nav #btm-universal-reset:hover{transform:translateY(-1px);color:#f0c4c8;border-color:rgba(220,105,115,.8);background:linear-gradient(145deg,rgba(68,29,35,.86),rgba(34,18,22,.86));box-shadow:0 0 0 1px rgba(220,105,115,.08),0 0 18px rgba(210,82,94,.12)}.btm-nav #btm-universal-reset:active{transform:translateY(0) scale(.985)}
.btm-reset-backdrop{position:fixed;inset:0;z-index:10000;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(3,8,12,.58);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);opacity:0;visibility:hidden;transition:opacity .26s ease,visibility 0s linear .26s}.btm-reset-backdrop.is-open{opacity:1;visibility:visible;transition:opacity .26s ease,visibility 0s linear 0s}.btm-reset-dialog{width:min(440px,100%);padding:25px;border:1px solid #3a5868;border-radius:10px;background:linear-gradient(145deg,#14242e,#0a151c);box-shadow:0 24px 80px rgba(0,0,0,.52),0 0 32px rgba(76,145,180,.08);transform:translateY(10px) scale(.985);opacity:.96;transition:transform .26s cubic-bezier(.2,.8,.2,1),opacity .26s ease}.btm-reset-backdrop.is-open .btm-reset-dialog{transform:none;opacity:1}.btm-reset-dialog .ey{margin-bottom:7px;color:#66b9df;font:9px 'JetBrains Mono';letter-spacing:.24em}.btm-reset-dialog h3{margin:0;color:#e8f0f4;font:400 27px Anton,sans-serif;text-transform:uppercase}.btm-reset-dialog p{margin:11px 0 21px;color:#8195a3;font-size:13px;line-height:1.5}.btm-reset-dialog .btm-reset-actions{display:flex;justify-content:flex-end;gap:9px}.btm-reset-dialog button{min-width:92px;cursor:pointer;border-radius:5px;padding:10px 14px;font:10px 'JetBrains Mono';font-weight:700;transition:transform .18s ease,background .18s ease,border-color .18s ease,box-shadow .18s ease}.btm-reset-cancel{color:#b9c8d0;background:#0b151c;border:1px solid #294656}.btm-reset-cancel:hover{background:#13232d;border-color:#456579;transform:translateY(-1px)}.btm-reset-confirm{color:#f4dfe1;background:#431d23;border:1px solid #81434b}.btm-reset-confirm:hover{background:#5a252d;border-color:#b45c66;box-shadow:0 0 18px rgba(190,72,86,.14);transform:translateY(-1px)}
@media(max-width:800px){#btm-universal-reset{margin-left:0;width:100%;grid-column:1/-1}.btm-reset-dialog{padding:21px}}@media(prefers-reduced-motion:reduce){#btm-universal-reset,.btm-reset-backdrop,.btm-reset-dialog,.btm-reset-dialog button{transition:none!important}}
`;
function installStyles(){if($('#btm-universal-reset-style'))return;const s=document.createElement('style');s.id='btm-universal-reset-style';s.textContent=css;document.head.appendChild(s)}
function installButton(){const nav=$('.btm-nav');if(!nav||$('#btm-universal-reset'))return;const b=document.createElement('button');b.id='btm-universal-reset';b.type='button';b.textContent='RESET / ERASE';b.title='Reset the currently selected day or week';nav.appendChild(b);b.addEventListener('click',openConfirm)}
function ensureModal(){let r=$('#btm-universal-reset-modal');if(r)return r;r=document.createElement('div');r.id='btm-universal-reset-modal';r.className='btm-reset-backdrop';r.setAttribute('aria-hidden','true');r.innerHTML='<div class="btm-reset-dialog" role="dialog" aria-modal="true" aria-labelledby="btmResetTitle"><div class="ey">DESTRUCTIVE ACTION</div><h3 id="btmResetTitle">ARE YOU SURE?</h3><p id="btmResetMessage"></p><div class="btm-reset-actions"><button type="button" class="btm-reset-cancel">CANCEL</button><button type="button" class="btm-reset-confirm">ERASE</button></div></div>';document.body.appendChild(r);r.addEventListener('click',e=>{if(e.target===r)closeModal()});r.querySelector('.btm-reset-cancel').addEventListener('click',closeModal);r.querySelector('.btm-reset-confirm').addEventListener('click',()=>{if(window.__btmPendingReset){const fn=window.__btmPendingReset;window.__btmPendingReset=null;fn()}closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&r.classList.contains('is-open'))closeModal()});return r}
function openConfirm(){const x=selection(),r=ensureModal(),msg=$('#btmResetMessage');if(x.type==='day'){const d=dateFor(x.week,x.day);msg.textContent=`You're about to erase the data for ${d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}. This action cannot be undone.`;window.__btmPendingReset=()=>resetDay(x)}else{msg.textContent=`You're about to erase all tracked data for Week ${x.week}. Other weeks will remain untouched. This action cannot be undone.`;window.__btmPendingReset=()=>resetWeek(x.week)}r.classList.add('is-open');r.setAttribute('aria-hidden','false');r.querySelector('.btm-reset-cancel').focus()}
function closeModal(){const r=$('#btm-universal-reset-modal');if(!r)return;r.classList.remove('is-open');r.setAttribute('aria-hidden','true');window.__btmPendingReset=null}
function resetDay(x){if(x.section==='food'){const d=read('btm_nutrition_unified',{});delete d[dateKey(x.week,x.day)];write('btm_nutrition_unified',d);const log=read('btm_food_log_v1',{});delete log[dateKey(x.week,x.day)];write('btm_food_log_v1',log)}else if(x.section==='running'){const d=read('btm_running',{});delete d[`w${x.week}s${x.day}`];write('btm_running',d)}else if(x.section==='sleep'){const d=read('btm_sleep_v2',{});delete d[dateKey(x.week,x.day)];write('btm_sleep_v2',d)}refresh(x)}
function resetWeek(w){const food=read('btm_nutrition_unified',{}),log=read('btm_food_log_v1',{}),run=read('btm_running',{}),sleep=read('btm_sleep_v2',{}),progress=read('btm_progress',{});for(let d=0;d<7;d++){const k=dateKey(w,d);delete food[k];delete log[k];delete sleep[k];delete run[`w${w}s${d}`]}Object.keys(progress).forEach(k=>{if(k.startsWith(w+'|'))delete progress[k]});write('btm_nutrition_unified',food);write('btm_food_log_v1',log);write('btm_running',run);write('btm_sleep_v2',sleep);write('btm_progress',progress);const body=read('btm_body_tracking',{});delete body[w];write('btm_body_tracking',body);refresh({type:'week',section:section(),week:w})}
function refresh(x){window.dispatchEvent(new CustomEvent('btm:data-changed',{detail:x}));const s=section();setTimeout(()=>{if(s==='food')$('#foodDays .day.active')?.click();else if(s==='running')$('#runDays .day.active')?.click();else if(s==='sleep')$('#sleepDays .day.active')?.click();else if(s==='progress')$('#progressBtn')?.click();else $('#weekGrid .week.active')?.click()},0)}
function boot(){installStyles();installButton();ensureModal();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
