(()=>{
'use strict';
const WEEKS=window.BTM_WEEKS||[],PROGRAM=window.BTM_TRAINING_WEEKS||{};
const EX_KEY='btm_training_exercise_completion_v2',LOG_KEY='btm_progress';
const CLAIM_KEY='btm_achievement_claims_v1',TITLE_KEY='btm_equipped_title_v1';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const exKey=(w,d,e)=>`w${w}:d${d}:e${e}`;
const logKey=(w,d,e)=>`${w}|${d}|${e}`;
const data=()=>({completions:read(EX_KEY,{}),logs:read(LOG_KEY,{})});
const countExercises=c=>Object.values(c).filter(Boolean).length;
function weekComplete(w,c){const days=(PROGRAM[w]||{}).days||[];return days.length>0&&days.every((d,di)=>d.exercises.every((_,ei)=>!!c[exKey(w,di,ei)]))}
function completeWeeks(c){return WEEKS.filter(w=>weekComplete(w.id,c)).length}
function trainingDaysCompleted(c){let n=0;WEEKS.forEach(w=>(PROGRAM[w.id]?.days||[]).forEach((d,di)=>{if(d.exercises.length&&d.exercises.every((_,ei)=>!!c[exKey(w.id,di,ei)]))n++}));return n}
function cleanCount(c,l){let n=0;WEEKS.forEach(w=>(PROGRAM[w.id]?.days||[]).forEach((d,di)=>d.exercises.forEach((_,ei)=>{if(c[exKey(w.id,di,ei)]&&l[logKey(w.id,di,ei)]?.feel==='clean')n++})));return n}
function perfectWeekCount(c,l){let n=0;WEEKS.forEach(w=>{const days=(PROGRAM[w.id]?.days||[]);if(days.length&&weekComplete(w.id,c)&&days.every((d,di)=>d.exercises.every((_,ei)=>l[logKey(w.id,di,ei)]?.feel==='clean')))n++});return n}
function achievementDefinitions(c,l){const completed=countExercises(c),weeks=completeWeeks(c),clean=cleanCount(c,l),days=trainingDaysCompleted(c),perfect=perfectWeekCount(c,l);return[
{id:'first_rep',title:'FIRST REP',description:'Complete your first exercise.',requirement:'Complete 1 exercise.',current:Math.min(completed,1),target:1,titleReward:'ROOKIE'},
{id:'no_excuses',title:'NO EXCUSES',description:'Complete 10 exercises.',requirement:'Complete 10 exercises.',current:Math.min(completed,10),target:10,titleReward:'NO EXCUSES'},
{id:'clean_machine',title:'CLEAN MACHINE',description:'Complete 10 exercises as CLEAN.',requirement:'Complete 10 exercises rated CLEAN.',current:Math.min(clean,10),target:10,titleReward:'CLEAN MACHINE'},
{id:'iron_week',title:'IRON WEEK',description:'Complete every exercise in a Week.',requirement:'Complete 1 full Week.',current:Math.min(weeks,1),target:1,titleReward:'IRON'},
{id:'halfway',title:'HALFWAY',description:'Complete 6 full Weeks.',requirement:'Complete 6 full Weeks.',current:Math.min(weeks,6),target:6,titleReward:'HALFWAY'},
{id:'perfect_week',title:'PERFECT WEEK',description:'Finish a Week with every exercise rated CLEAN.',requirement:'Complete 1 full Week with every exercise rated CLEAN.',current:Math.min(perfect,1),target:1,titleReward:'PERFECT'},
{id:'consistent',title:'CONSISTENT',description:'Reach 50% training-day consistency.',requirement:'Complete 18 of 36 training days.',current:Math.min(days,18),target:18,titleReward:'CONSISTENT'},
{id:'legend',title:'LEGEND',description:'Complete Week 12.',requirement:'Complete Week 12.',current:weekComplete(12,c)?1:0,target:1,titleReward:'LEGEND'}
]}
function normalizedClaims(){const claims=read(CLAIM_KEY,{});return claims&&typeof claims==='object'?claims:{}}
function models(){const {completions,logs}=data(),claims=normalizedClaims();return achievementDefinitions(completions,logs).map(a=>{const pct=Math.min(100,Math.round(a.current/a.target*1000)/10),unlocked=a.current>=a.target,claimed=claims[a.id]===true;return {...a,progress:pct,unlocked,claimable:unlocked&&!claimed,claimed}})}
const logoMap={
 first_rep:{label:'FIRST REP',path:'M12 3v5m0 8v5M3 12h5m8 0h5M5.6 5.6l3.5 3.5m6 6 3.3 3.3m0-12.8-3.3 3.5m-6 6-3.5 3.3'},
 no_excuses:{label:'NO EXCUSES',path:'M5 12a7 7 0 1 0 14 0 7 7 0 0 0-14 0Zm4 0 2 2 4-5'},
 clean_machine:{label:'CLEAN MACHINE',path:'M12 3 4.5 7v5c0 4.5 3.2 7.3 7.5 9 4.3-1.7 7.5-4.5 7.5-9V7L12 3Zm-3 9 2 2 4-4'},
 iron_week:{label:'IRON WEEK',path:'M8 3h8v3h2v5l-3 2v5H9v-5l-3-2V6h2V3Zm0 3h8'},
 halfway:{label:'HALFWAY',path:'M12 3v18M3 12h18M5.5 5.5l13 13m0-13-13 13'},
 perfect_week:{label:'PERFECT WEEK',path:'M12 3l2.7 5.5 6 .9-4.4 4.3 1 6.1-5.3-2.8-5.3 2.8 1-6.1L3.3 9.4l6-.9L12 3Z'},
 consistent:{label:'CONSISTENT',path:'M4 17h4V7H4v10Zm6 0h4V4h-4v13Zm6 0h4v-7h-4v7Z'},
 legend:{label:'LEGEND',path:'M12 3l2.1 4.8 5.2.5-3.9 3.4 1.2 5-4.6-2.7-4.6 2.7 1.2-5-3.9-3.4 5.2-.5L12 3Z'}
};
function achievementLogo(id,size=22){const p=logoMap[id]||logoMap.first_rep;return `<span class="achievement-logo" aria-hidden="true"><svg viewBox="0 0 24 24" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none"><path d="${p.path}" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg></span>`}
const css=`
.achievement-card{position:relative;overflow:hidden;transition:border-color .2s ease,background .2s ease,box-shadow .2s ease,transform .18s ease}.achievement-card.claimed{border-color:#55bd72!important;background:linear-gradient(145deg,rgba(63,156,91,.28),rgba(8,27,17,.96))!important;box-shadow:0 0 22px rgba(91,190,116,.15)!important}.achievement-card.claimed .achievement-icon{transform:scale(1.05)}
.achievement-progress{margin-top:10px}.achievement-progress-head{display:flex;justify-content:space-between;gap:10px;font:800 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.06em;color:var(--muted)}.achievement-progress-track{height:6px;margin-top:6px;border-radius:99px;overflow:hidden;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.05)}.achievement-progress-fill{height:100%;width:0;border-radius:99px;background:linear-gradient(90deg,#66b9df,#7bd5f5);transition:width .35s ease}.achievement-card.claimed .achievement-progress-fill{background:linear-gradient(90deg,#55bd72,#8be39a)}
.achievement-requirement{margin-top:7px;font-size:8px!important;color:var(--muted)!important}.achievement-actions{display:flex;align-items:center;justify-content:flex-end;min-height:30px;margin-top:8px}.achievement-claim{border:1px solid #55bd72;border-radius:9px;background:rgba(85,189,114,.12);color:#91e19d;padding:7px 12px;font:900 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;transition:transform .12s ease,box-shadow .18s ease,background .18s ease}.achievement-claim:active{transform:scale(.96)}.achievement-claim:hover{box-shadow:0 0 14px rgba(91,190,116,.25)}.achievement-claimed{font:900 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;color:#91e19d}.achievement-card.just-claimed{animation:achievementClaim .55s ease}.achievement-claim-pop{position:absolute;right:14px;top:12px;font:900 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;color:#91e19d;opacity:0;animation:achievementPop 1s ease forwards;pointer-events:none}
.achievement-main{display:flex;align-items:center;gap:10px}.achievement-icon{width:34px;height:34px;display:grid;place-items:center;flex:0 0 34px;border:1px solid rgba(102,185,223,.28);border-radius:10px;color:#8ed6ee;background:rgba(102,185,223,.06);box-shadow:inset 0 1px rgba(255,255,255,.04)}.achievement-card.claimed .achievement-icon{color:#8be39a;border-color:rgba(85,189,114,.45);background:rgba(85,189,114,.08)}.achievement-copy{min-width:0}.achievement-logo{display:inline-flex;align-items:center;justify-content:center;color:inherit}.achievement-name{display:block}.achievement-card.locked .achievement-icon{opacity:.45}
@keyframes achievementClaim{0%{transform:scale(1)}45%{transform:scale(1.012)}100%{transform:scale(1)}}@keyframes achievementPop{0%{opacity:0;transform:translateY(4px)}25%{opacity:1;transform:translateY(0)}75%{opacity:1}100%{opacity:0;transform:translateY(-7px)}}
.title-section{margin-top:8px;padding:10px 12px;border:1px solid var(--line);border-radius:14px;background:linear-gradient(145deg,#0d1820,#081118);position:relative}.title-section-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.title-kicker{font:800 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.12em;color:var(--muted)}.title-current{margin-top:5px;width:100%;display:flex;align-items:center;gap:8px;min-height:40px;padding:8px 10px;border:1px solid var(--line);border-radius:11px;background:rgba(255,255,255,.025);color:var(--text);text-align:left;cursor:pointer;transition:transform .14s ease,border-color .18s ease,background .18s ease,box-shadow .18s ease}.title-current:hover{border-color:rgba(102,185,223,.5);box-shadow:0 6px 20px rgba(0,0,0,.15)}.title-current:active{transform:scale(.985)}.title-current-text{flex:1;font:900 11px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em}.title-current.muted .title-current-text{color:var(--muted)}.title-chevron{font-size:12px;color:var(--muted);transition:transform .22s ease}.title-section.open .title-chevron{transform:rotate(180deg)}.title-dropdown{overflow:hidden;max-height:0;opacity:0;transform:translateY(-5px);transition:max-height .24s cubic-bezier(.2,.8,.2,1),opacity .18s ease,transform .24s cubic-bezier(.2,.8,.2,1);pointer-events:none}.title-section.open .title-dropdown{max-height:420px;opacity:1;transform:translateY(0);pointer-events:auto}.title-dropdown-inner{padding-top:7px;display:grid;gap:5px}.title-choice{width:100%;display:flex;align-items:center;gap:8px;min-height:40px;border:1px solid var(--line);border-radius:10px;background:rgba(255,255,255,.02);color:var(--muted);padding:7px 9px;text-align:left;font:800 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.06em;transition:transform .14s ease,background .18s ease,border-color .18s ease,color .18s ease}.title-choice:hover{border-color:rgba(102,185,223,.45);background:rgba(102,185,223,.06);color:var(--text)}.title-choice:active{transform:scale(.985)}.title-choice.active{border-color:#66b9df;color:#e5faff;background:rgba(102,185,223,.1);box-shadow:0 0 14px rgba(102,185,223,.08)}.title-choice .achievement-logo{color:#8ed6ee}.title-empty{color:var(--muted)!important}
.equipped-title-header{display:flex;align-items:center;gap:6px;margin-top:5px;font:900 9px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;color:var(--blue)}.equipped-title-header .achievement-logo{color:inherit}
@media(prefers-reduced-motion:reduce){.title-dropdown,.title-chevron,.title-current,.title-choice{transition:none!important}.achievement-card.just-claimed{animation:none!important}}
`;
function injectCSS(){if(document.getElementById('achievementSystemCSS'))return;const s=document.createElement('style');s.id='achievementSystemCSS';s.textContent=css;document.head.appendChild(s)}
function rewardForTitle(title){return achievementDefinitions(data().completions,data().logs).find(a=>a.titleReward===title)?.id||null}
function ensureTitleSection(){const header=document.querySelector('.app-header');if(!header)return;let el=document.getElementById('titleSection');if(!el){el=document.createElement('section');el.id='titleSection';el.className='title-section';const nav=header.querySelector('.main-nav');header.insertBefore(el,nav||null)}renderTitle(el)}
function renderTitle(el){const equipped=localStorage.getItem(TITLE_KEY)||'';const claims=normalizedClaims();const available=achievementDefinitions(data().completions,data().logs).filter(a=>claims[a.id]===true);const unique=[...new Map(available.map(a=>[a.titleReward,a])).values()];const equippedId=rewardForTitle(equipped);el.classList.remove('open');el.innerHTML=`<div class="title-section-head"><span class="title-kicker">TITLE</span><span class="title-kicker">${unique.length} UNLOCKED</span></div><button type="button" class="title-current ${equipped?'':'muted'}" aria-expanded="false"><span>${equippedId?achievementLogo(equippedId,19):achievementLogo('first_rep',19)}</span><span class="title-current-text">${equipped?escapeHTML(equipped):'NO TITLE EQUIPPED'}</span><span class="title-chevron">⌄</span></button><div class="title-dropdown"><div class="title-dropdown-inner">${unique.length?unique.map(a=>`<button type="button" class="title-choice ${equipped===a.titleReward?'active':''}" data-title="${escapeHTML(a.titleReward)}">${achievementLogo(a.id,18)}<span>${escapeHTML(a.titleReward)}</span></button>`).join(''):'<div class="title-empty">CLAIM AN ACHIEVEMENT TO UNLOCK A TITLE</div>'}</div></div>`;const current=el.querySelector('.title-current');current.onclick=()=>{const open=!el.classList.contains('open');el.classList.toggle('open',open);current.setAttribute('aria-expanded',String(open))};el.querySelectorAll('.title-choice').forEach(b=>b.onclick=()=>{localStorage.setItem(TITLE_KEY,b.dataset.title);el.classList.remove('open');renderTitle(el);renderTitleHeader()})}
function renderTitleHeader(){const header=document.querySelector('.app-header');if(!header)return;let badge=document.getElementById('equippedTitleHeader');const equipped=localStorage.getItem(TITLE_KEY)||'';if(!equipped){badge?.remove();return}const id=rewardForTitle(equipped);if(!badge){badge=document.createElement('div');badge.id='equippedTitleHeader';badge.className='equipped-title-header';const eyebrow=header.querySelector('.eyebrow');eyebrow?.insertAdjacentElement('afterend',badge)}badge.innerHTML=achievementLogo(id||'first_rep',17)+`<span>${escapeHTML(equipped)}</span>`}
function decorateAchievements(){const root=document.getElementById('achievementList');if(!root)return;const items=models(),existing=[...root.querySelectorAll('.achievement')];root.innerHTML=items.map(a=>`<div class="achievement achievement-card ${a.unlocked?'unlocked':'locked'}${a.claimed?' claimed':''}" data-achievement-id="${a.id}"><div class="achievement-main"><div class="achievement-icon">${achievementLogo(a.id,20)}</div><div class="achievement-copy"><div class="achievement-name">${escapeHTML(a.title)}</div><div class="achievement-note">${escapeHTML(a.description)}</div></div></div><div class="achievement-requirement">${escapeHTML(a.requirement)}</div><div class="achievement-progress"><div class="achievement-progress-head"><span>${a.current} / ${a.target}</span><span>${a.progress}%</span></div><div class="achievement-progress-track"><div class="achievement-progress-fill" style="width:${a.progress}%"></div></div></div><div class="achievement-actions">${a.claimed?'<span class="achievement-claimed">✓ CLAIMED · '+escapeHTML(a.titleReward)+'</span>':a.claimable?'<button type="button" class="achievement-claim">CLAIM</button>':''}</div></div>`).join('');const count=document.getElementById('achievementCount');if(count)count.textContent=items.filter(a=>a.unlocked).length+' / '+items.length+' UNLOCKED';root.querySelectorAll('.achievement-claim').forEach(b=>b.onclick=()=>claim(b.closest('.achievement-card').dataset.achievementId));items.forEach(a=>{const old=existing.find(e=>e.dataset.achievementId===a.id);if(a.claimed&&!old?.classList.contains('claimed')){const card=root.querySelector(`[data-achievement-id="${a.id}"]`);card?.classList.add('just-claimed')}})}
function claim(id){const a=models().find(x=>x.id===id);if(!a||!a.claimable)return;const claims=normalizedClaims();claims[id]=true;write(CLAIM_KEY,claims);decorateAchievements();ensureTitleSection();renderTitleHeader();const card=document.querySelector(`[data-achievement-id="${id}"]`);if(card){card.classList.add('just-claimed');const pop=document.createElement('span');pop.className='achievement-claim-pop';pop.textContent='TITLE UNLOCKED · '+a.titleReward;card.appendChild(pop)}try{navigator.vibrate?.([15,30,15])}catch{}}
let last='';
function refresh(){ensureTitleSection();renderTitleHeader();const root=document.getElementById('achievementList');if(!root)return;const sig=JSON.stringify({models:models(),claims:normalizedClaims(),title:localStorage.getItem(TITLE_KEY)||''});if(sig!==last){last=sig;decorateAchievements()}}
function boot(){injectCSS();refresh();const observer=new MutationObserver(()=>{setTimeout(refresh,0)});observer.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setInterval(refresh,400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.BTM_ACHIEVEMENTS={refresh,models};
})();
