(()=>{
'use strict';
const E=window.BTM_PROGRESS_ENGINE;
if(!E){console.error('BTM progress engine missing');return}
const WEEKS=window.BTM_WEEKS||[],PROGRAM=window.BTM_TRAINING_WEEKS||{};
const EX_KEY='btm_training_exercise_completion_v2',LOG_KEY='btm_progress';
const CLAIM_KEY='btm_achievement_claims_v1',TITLE_KEY='btm_equipped_title_v1';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const escapeHTML=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const exKey=(w,d,e)=>`w${w}:d${d}:e${e}`;
const logKey=(w,d,e)=>`${w}|${d}|${e}`;
const data=()=>({completions:read(EX_KEY,{}),logs:read(LOG_KEY,{})});
function metrics(){const {completions,logs}=data();const all=E.calculateAll();const completed=all.program.completedExercises;const clean=all.clean;const weeks=all.weekMetrics.filter(x=>x.complete).length;const days=all.completedTrainingDays;let perfect=0;WEEKS.forEach(w=>{const x=all.weekMetrics.find(m=>m.week===w.id);if(x?.complete){const d=PROGRAM[w.id]?.days||[];if(d.every((day,di)=>day.exercises.every((_,ei)=>logs[logKey(w.id,di,ei)]?.feel==='clean')))perfect++}});return{completions,logs,completed,clean,weeks,days,perfect,week12:!!all.weekMetrics.find(x=>x.week===12)?.complete}}
function achievementDefinitions(){const m=metrics();return[
{id:'first_rep',title:'FIRST REP',description:'Complete your first exercise.',requirement:'Complete 1 exercise.',current:Math.min(m.completed,1),target:1,titleReward:'ROOKIE',icon:'◆'},
{id:'no_excuses',title:'NO EXCUSES',description:'Complete 10 exercises.',requirement:'Complete 10 exercises.',current:Math.min(m.completed,10),target:10,titleReward:'NO EXCUSES',icon:'▲'},
{id:'clean_machine',title:'CLEAN MACHINE',description:'Complete 10 exercises as CLEAN.',requirement:'Complete 10 exercises rated CLEAN.',current:Math.min(m.clean,10),target:10,titleReward:'CLEAN MACHINE',icon:'✦'},
{id:'iron_week',title:'IRON WEEK',description:'Complete every exercise in a Week.',requirement:'Complete 1 full Week.',current:Math.min(m.weeks,1),target:1,titleReward:'IRON',icon:'⬢'},
{id:'halfway',title:'HALFWAY',description:'Complete 6 full Weeks.',requirement:'Complete 6 full Weeks.',current:Math.min(m.weeks,6),target:6,titleReward:'HALFWAY',icon:'◈'},
{id:'perfect_week',title:'PERFECT WEEK',description:'Finish a Week with every exercise rated CLEAN.',requirement:'Complete 1 full Week with every exercise rated CLEAN.',current:Math.min(m.perfect,1),target:1,titleReward:'PERFECT',icon:'✧'},
{id:'consistent',title:'CONSISTENT',description:'Reach 50% training-day consistency.',requirement:'Complete 18 of 36 training days.',current:Math.min(m.days,18),target:18,titleReward:'CONSISTENT',icon:'≋'},
{id:'legend',title:'LEGEND',description:'Complete Week 12.',requirement:'Complete Week 12.',current:m.week12?1:0,target:1,titleReward:'LEGEND',icon:'★'}
]}
function normalizedClaims(){const claims=read(CLAIM_KEY,{});return claims&&typeof claims==='object'?claims:{}}
function models(){const claims=normalizedClaims();return achievementDefinitions().map(a=>{const p=E.calculateAchievementProgress(a.current,a.target),claimed=claims[a.id]===true;return {...a,current:p.current,target:p.target,progress:p.percent,unlocked:p.unlocked,claimable:p.unlocked&&!claimed,claimed}})}
const css=`.achievement-card{position:relative;overflow:hidden;transition:border-color .2s ease,background .2s ease,box-shadow .2s ease,transform .18s ease}.achievement-card.claimed{border-color:#55bd72!important;background:linear-gradient(145deg,rgba(63,156,91,.28),rgba(8,27,17,.96))!important;box-shadow:0 0 22px rgba(91,190,116,.15)!important}.achievement-card.claimed .achievement-icon{transform:scale(1.05)}.achievement-progress{margin-top:10px}.achievement-progress-head{display:flex;justify-content:space-between;gap:10px;font:800 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.06em;color:var(--muted)}.achievement-progress-track{height:6px;margin-top:6px;border-radius:99px;overflow:hidden;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.05)}.achievement-progress-fill{height:100%;width:0;border-radius:99px;background:linear-gradient(90deg,#66b9df,#7bd5f5);transition:width .35s ease}.achievement-card.claimed .achievement-progress-fill{background:linear-gradient(90deg,#55bd72,#8be39a)}.achievement-requirement{margin-top:7px;font-size:8px!important;color:var(--muted)!important}.achievement-actions{display:flex;align-items:center;justify-content:flex-end;min-height:30px;margin-top:8px}.achievement-claim{border:1px solid #55bd72;border-radius:9px;background:rgba(85,189,114,.12);color:#91e19d;padding:7px 12px;font:900 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;transition:transform .12s ease,box-shadow .18s ease,background .18s ease}.achievement-claim:active{transform:scale(.96)}.achievement-claim:hover{box-shadow:0 0 14px rgba(91,190,116,.25)}.achievement-claimed{font:900 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;color:#91e19d}.achievement-card.just-claimed{animation:achievementClaim .55s ease}.achievement-claim-pop{position:absolute;right:14px;top:12px;font:900 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;color:#91e19d;opacity:0;animation:achievementPop 1s ease forwards;pointer-events:none}@keyframes achievementClaim{0%{transform:scale(1)}45%{transform:scale(1.012)}100%{transform:scale(1)}}@keyframes achievementPop{0%{opacity:0;transform:translateY(4px)}25%{opacity:1;transform:translateY(0)}75%{opacity:1}100%{opacity:0;transform:translateY(-7px)}}
.title-section{margin-top:8px;padding:12px;border:1px solid var(--line);border-radius:16px;background:linear-gradient(145deg,#0d1820,#081118);text-align:center}.title-section-head{display:none}.title-equipped{display:flex;align-items:center;justify-content:center;gap:8px;font:900 20px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;color:#fff;text-shadow:0 0 10px rgba(190,235,255,.35),0 0 24px rgba(102,185,223,.2)}.title-equipped-logo{display:inline-flex;align-items:center;justify-content:center;width:25px;height:25px;font-size:15px;color:#ccefff;text-shadow:0 0 12px rgba(102,185,223,.6)}.title-empty{color:var(--muted)!important;text-shadow:none}.title-select{position:relative;margin:10px auto 0;max-width:260px}.title-select-trigger{width:100%;display:flex;align-items:center;justify-content:center;gap:6px;border:1px solid var(--line);border-radius:10px;background:rgba(102,185,223,.06);color:var(--muted);padding:8px 10px;font:900 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;transition:transform .16s ease,background .2s ease,border-color .2s ease,box-shadow .2s ease}.title-select-trigger:active{transform:scale(.97);background:rgba(102,185,223,.12)}.title-select-trigger .chevron{transition:transform .22s ease}.title-select.open .chevron{transform:rotate(180deg)}.title-options{display:grid;grid-template-rows:0fr;opacity:0;overflow:hidden;transition:grid-template-rows .24s ease,opacity .2s ease}.title-select.open .title-options{grid-template-rows:1fr;opacity:1}.title-options-inner{min-height:0;overflow:hidden;display:flex;flex-direction:column;gap:5px;padding-top:0;transition:padding-top .24s ease}.title-select.open .title-options-inner{padding-top:6px}.title-choice{display:flex;align-items:center;justify-content:center;gap:7px;width:100%;border:1px solid var(--line);border-radius:9px;background:rgba(255,255,255,.025);color:var(--muted);padding:8px 10px;font:800 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.06em;transition:transform .14s ease,background .18s ease,border-color .18s ease,box-shadow .18s ease}.title-choice:active{transform:scale(.98)}.title-choice:hover{border-color:#66b9df;background:rgba(102,185,223,.08);box-shadow:0 0 12px rgba(102,185,223,.12)}.title-choice.active{border-color:#66b9df;color:#e5faff;background:rgba(102,185,223,.1);box-shadow:0 0 12px rgba(102,185,223,.1)}.title-choice-logo{font-size:11px;color:#ccefff}.title-section.compact{padding:8px}.title-section.compact .title-equipped{font-size:16px}`;
function injectCSS(){if(document.getElementById('achievementSystemCSS'))document.getElementById('achievementSystemCSS').remove();const s=document.createElement('style');s.id='achievementSystemCSS';s.textContent=css;document.head.appendChild(s)}
function iconForTitle(title){return achievementDefinitions().find(a=>a.titleReward===title)?.icon||'◆'}
function ensureTitleSection(){const header=document.querySelector('.app-header');if(!header)return;let el=document.getElementById('titleSection');if(!el){el=document.createElement('section');el.id='titleSection';el.className='title-section';const nav=header.querySelector('.main-nav');header.insertBefore(el,nav||null)}renderTitle(el)}
function renderTitle(el){const equipped=localStorage.getItem(TITLE_KEY)||'';const claims=normalizedClaims();const available=achievementDefinitions().filter(a=>claims[a.id]===true);el.innerHTML=`<div class="title-equipped ${equipped?'':'title-empty'}">${equipped?`<span class="title-equipped-logo">${iconForTitle(equipped)}</span>${escapeHTML(equipped)}`:'NO TITLE EQUIPPED'}</div>${available.length?`<div class="title-select"><button type="button" class="title-select-trigger" aria-expanded="false"><span>SELECT TITLE</span><span class="chevron">▾</span></button><div class="title-options"><div class="title-options-inner">${available.map(a=>`<button type="button" class="title-choice ${equipped===a.titleReward?'active':''}" data-title="${escapeHTML(a.titleReward)}"><span class="title-choice-logo">${a.icon}</span>${escapeHTML(a.titleReward)}</button>`).join('')}</div></div></div>`:''}`;const select=el.querySelector('.title-select');if(!select)return;const trigger=select.querySelector('.title-select-trigger');trigger.onclick=()=>{const open=select.classList.toggle('open');trigger.setAttribute('aria-expanded',open?'true':'false')};select.querySelectorAll('.title-choice').forEach(b=>b.onclick=()=>{localStorage.setItem(TITLE_KEY,b.dataset.title);select.classList.remove('open');renderTitle(el);renderTitleHeader()})}
function renderTitleHeader(){const header=document.querySelector('.app-header');if(!header)return;let badge=document.getElementById('equippedTitleHeader');badge?.remove()}
function decorateAchievements(){const root=document.getElementById('achievementList');if(!root)return;const items=models(),existing=[...root.querySelectorAll('.achievement')];root.innerHTML=items.map(a=>`<div class="achievement achievement-card${a.unlocked?' unlocked':''}${a.claimed?' claimed':''}" data-achievement-id="${a.id}"><div class="achievement-icon">${a.icon}</div><div class="achievement-name">${escapeHTML(a.title)}</div><div class="achievement-note">${escapeHTML(a.description)}</div><div class="achievement-requirement">${escapeHTML(a.requirement)}</div><div class="achievement-progress"><div class="achievement-progress-head"><span>${a.current} / ${a.target}</span><span>${a.progress}%</span></div><div class="achievement-progress-track"><div class="achievement-progress-fill" style="width:${a.progress}%"></div></div></div><div class="achievement-actions">${a.claimed?'<span class="achievement-claimed">✓ CLAIMED · '+escapeHTML(a.titleReward)+'</span>':a.claimable?'<button type="button" class="achievement-claim">CLAIM</button>':''}</div></div>`).join('');const count=document.getElementById('achievementCount');if(count)count.textContent=items.filter(a=>a.unlocked).length+' / '+items.length+' UNLOCKED';root.querySelectorAll('.achievement-claim').forEach(b=>b.onclick=()=>claim(b.closest('.achievement-card').dataset.achievementId));items.forEach(a=>{const old=existing.find(e=>e.dataset.achievementId===a.id);if(a.claimed&&!old?.classList.contains('claimed')){const card=root.querySelector(`[data-achievement-id="${a.id}"]`);card?.classList.add('just-claimed')}})}
function claim(id){const a=models().find(x=>x.id===id);if(!a||!a.claimable)return;const claims=normalizedClaims();claims[id]=true;write(CLAIM_KEY,claims);decorateAchievements();ensureTitleSection();const card=document.querySelector(`[data-achievement-id="${id}"]`);if(card){card.classList.add('just-claimed');const pop=document.createElement('span');pop.className='achievement-claim-pop';pop.textContent='TITLE UNLOCKED · '+a.titleReward;card.appendChild(pop)}try{navigator.vibrate?.([15,30,15])}catch{}}
let last='';
function refresh(){ensureTitleSection();const root=document.getElementById('achievementList');if(!root)return;const sig=JSON.stringify({models:models(),claims:normalizedClaims(),title:localStorage.getItem(TITLE_KEY)||''});if(sig!==last){last=sig;decorateAchievements()}}
function boot(){injectCSS();refresh();const observer=new MutationObserver(()=>{setTimeout(refresh,0)});observer.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setInterval(refresh,400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.BTM_ACHIEVEMENTS={refresh,models};
})();
