(()=>{
'use strict';
const WEEKS=window.BTM_WEEKS||[];
const PROGRAM=window.BTM_TRAINING_WEEKS||{};
const EX_KEY='btm_training_exercise_completion_v2';
const LOG_KEY='btm_progress';
const WEEK_KEY='btm_training_current_week_v1';
const RANK_QUOTES={NOVICE:'Every expert was once willing to begin.',BEGINNER:'Small steps become serious progress when you refuse to stop.',TRAINEE:'Consistency turns effort into ability.',APPRENTICE:'Skill grows when discipline becomes routine.',SKILLED:'You are no longer learning the work, you are becoming the work.',ADVANCED:'Discipline begins where excuses lose their power.',RECOVERY:'Recovery is not retreat, it is how strength prepares to rise again.',ELITE:'You earned your place by doing what most people abandon.',EXPERT:'Control your effort, sharpen your execution, raise your standard.',MASTER:'Mastery is built through consistency when motivation disappears.',GRANDMASTER:'At this level, discipline is no longer an action, it is an identity.',LEGEND:'The final level is not the end, it is proof of what you became.'};
const BLOCK=w=>w<=4?'FOUNDATION BLOCK':w<=6?'DIFFICULTY BLOCK':w===7?'DELOAD BLOCK':w<=9?'REBUILD BLOCK':w===10?'VARIATION BLOCK':'PEAK BLOCK';
const safeRead=(key,f)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??f}catch{return f}};
const safeWrite=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
let week=Number(localStorage.getItem(WEEK_KEY))||1;
if(!PROGRAM[week])week=1;
let completions=safeRead(EX_KEY,{});
let logs=safeRead(LOG_KEY,{});
let restSeconds=0,restTimer=null;
const $=id=>document.getElementById(id);
const meta=()=>WEEKS[week-1]||{id:week,rank:'WEEK '+week,color:'#66b9df'};
const program=()=>PROGRAM[week]||{days:[],deload:false};
const exerciseKey=(w,d,i)=>`w${w}:d${d}:e${i}`;
const logKey=(w,d,i)=>`${w}|${d}|${i}`;
const getLog=(d,i)=>logs[logKey(week,d,i)]||(logs[logKey(week,d,i)]={done:false,feel:'',sets:[],note:''});
const totalExercises=()=>WEEKS.reduce((sum,w)=>sum+(PROGRAM[w.id]?.days||[]).reduce((n,d)=>n+d.exercises.length,0),0);
const completedExercises=()=>Object.values(completions).filter(Boolean).length;
function haptic(pattern=8){if('vibrate' in navigator){try{navigator.vibrate(pattern)}catch{}}}
function persist(){safeWrite(EX_KEY,completions);safeWrite(LOG_KEY,logs);localStorage.setItem(WEEK_KEY,String(week))}
function save(){persist();renderAll();window.BTM_PROGRESS?.refresh?.()}
function isComplete(d,i){return !!completions[exerciseKey(week,d,i)]}
function setComplete(d,i,value){const k=exerciseKey(week,d,i);if(value)completions[k]=true;else delete completions[k]}
function weekComplete(w){const p=PROGRAM[w];if(!p?.days?.length)return false;return p.days.every((d,di)=>d.exercises.every((_,ei)=>!!completions[exerciseKey(w,di,ei)]))}
function completedWeeks(){return WEEKS.filter(w=>weekComplete(w.id)).length}
function renderHero(){const m=meta(),pct=Math.round((completedExercises()/Math.max(1,totalExercises()))*100);$('currentWeek').textContent='WEEK '+week;$('currentRank').textContent=m.rank;$('overallProgress').textContent=pct+'%';$('overallFill').style.width=pct+'%';$('rankQuote').textContent=RANK_QUOTES[m.rank]||'';$('deloadBadge').classList.toggle('hidden',!m.isDeload);$('weekCount').textContent=completedWeeks()+' / 12 COMPLETE'}
function renderWeeks(){const root=$('weekGrid');root.replaceChildren();WEEKS.forEach(w=>{const b=document.createElement('button');b.type='button';b.className='week-card'+(week===w.id?' active ':'')+(weekComplete(w.id)?' complete':'');b.style.setProperty('--week-color',w.color);const check=weekComplete(w.id)?'<span class="week-check">✓</span>':'';b.innerHTML=check+'<span class="week-number">WEEK '+w.id+'</span><span class="week-rank">'+w.rank+(w.isDeload?' · DELOAD':'')+'</span>';b.onclick=()=>{week=w.id;persist();haptic();renderAll();$('workoutSection').scrollIntoView({behavior:'smooth',block:'start'})};root.appendChild(b)})}
function renderBanner(){const m=meta(),root=$('workoutBanner');root.className='workout-banner'+(m.isDeload?' deload':'');root.innerHTML='<div class="banner-title">'+(m.isDeload?'RECOVERY · DELOAD':BLOCK(week))+'</div><p class="banner-note">'+(m.isDeload?'Training stress is deliberately reduced: fewer sets, easier variations and 4 RIR. Recover now so Weeks 8–12 can progress again.':'Complete the fixed prescription with clean form. RIR controls effort, while the Week configuration controls progression. Completion never rewrites future Weeks.')+'</p>';$('selectedWeekLabel').textContent='WEEK '+week+' · '+m.rank;$('selectedWeekStatus').textContent=weekComplete(week)?'COMPLETED':'IN PROGRESS'}
function metric(label,value,extra=''){return '<div class="metric '+extra+'"><div class="metric-label">'+label+'</div><div class="metric-value">'+value+'</div></div>'}
function renderWorkouts(){const root=$('workouts');root.replaceChildren();const p=program();p.days.forEach((day,di)=>{const box=document.createElement('section');box.className='day';box.dataset.dayIndex=di;const doneCount=day.exercises.reduce((n,_,ei)=>n+(isComplete(di,ei)?1:0),0);const head=document.createElement('div');head.className='day-head';head.innerHTML='<strong>'+escapeHTML(day.day)+'</strong><span>'+doneCount+' / '+day.exercises.length+' COMPLETE</span>';box.appendChild(head);day.exercises.forEach((ex,ei)=>box.appendChild(exerciseCard(ex,di,ei)));root.appendChild(box)});if(weekComplete(week)){const done=document.createElement('div');done.className='week-complete';done.textContent='✓ WEEK '+week+' COMPLETED';root.appendChild(done)}}
function exerciseCard(ex,di,ei){const done=isComplete(di,ei),log=getLog(di,ei),card=document.createElement('article');card.className='exercise-card'+(done?' complete':'');const variation=ex.variation&&ex.variation!==ex.name?'<div class="variation">'+escapeHTML(ex.variation)+'</div>':'';card.innerHTML='<div class="exercise-top"><div><div class="exercise-name">'+escapeHTML(ex.name)+'</div>'+variation+'</div></div><div class="metrics">'+metric('SETS × REPS',ex.sets+' × '+ex.reps)+metric('RIR',ex.rir,'rir')+'</div>';
const sets=document.createElement('div');sets.className='set-grid';const values=Array.isArray(log.sets)?log.sets:[];for(let i=0;i<ex.sets;i++){const input=document.createElement('input');input.className='set-input';input.inputMode='decimal';input.placeholder='Set '+(i+1);input.value=values[i]||'';input.addEventListener('input',()=>{const current=getLog(di,ei);current.sets[i]=input.value;persist();});sets.appendChild(input)}card.appendChild(sets);
const feelLabel=document.createElement('div');feelLabel.className='performance-label';feelLabel.textContent='PERFORMANCE';card.appendChild(feelLabel);const feel=document.createElement('div');feel.className='feel-row'+(done?'':' rating-disabled');['clean','mediocre','bad'].forEach(f=>{const b=document.createElement('button');b.type='button';b.className='feel-btn'+(log.feel===f?' active':'');b.textContent=f;b.disabled=!done;b.onclick=()=>{const current=getLog(di,ei);current.feel=f;persist();haptic();renderAll()};feel.appendChild(b)});card.appendChild(feel);
const note=document.createElement('textarea');note.className='exercise-note';note.rows=1;note.placeholder='Optional session note…';note.value=log.note||'';note.addEventListener('input',()=>{getLog(di,ei).note=note.value;persist()});card.appendChild(note);
const button=document.createElement('button');button.type='button';button.className='complete-btn'+(done?' done':'');button.textContent=done?'✓ COMPLETED':'COMPLETE';button.onclick=()=>{setComplete(di,ei,!done);const current=getLog(di,ei);current.done=!done;if(!done&&!current.feel)current.feel='';persist();haptic();renderAll();if(!done)startRest(90);setTimeout(()=>document.querySelector(`[data-day-index="${di}"] .exercise-card:nth-of-type(${ei+1})`)?.scrollIntoView({behavior:'smooth',block:'nearest'}),0)};card.appendChild(button);return card}
function todayInfo(){const now=new Date();const day=now.getDay();const map={2:0,4:1,5:2};if(map[day]!==undefined)return {index:map[day],today:true};const ordered=[2,4,5];let next=ordered.find(d=>d>day);if(next===undefined)next=ordered[0];return {index:ordered.indexOf(next),today:false}}
function renderToday(){const box=$('todayCard');const info=todayInfo(),p=program();const day=p.days[info.index];if(!day){box.className='today-card rest';box.innerHTML='<div class="today-kicker">TODAY</div><div class="today-title">REST / RECOVERY</div><div class="today-sub">Your training days are Tuesday, Thursday and Friday. Use today to recover.</div>';return}const done=day.exercises.filter((_,i)=>isComplete(info.index,i)).length;box.className='today-card '+(info.today?'ready':'rest');box.innerHTML='<div class="today-kicker">'+(info.today?'TODAY':'NEXT TRAINING DAY')+'</div><div class="today-title">'+escapeHTML(day.day.split(' · ')[0])+'</div><div class="today-sub">'+escapeHTML(day.day.split(' · ')[1]||'Training')+' · '+done+'/'+day.exercises.length+' exercises complete</div><div class="today-actions"><button class="today-action primary" id="startToday" type="button">START WORKOUT</button><button class="today-action" id="todayWeek" type="button">WEEK '+week+'</button></div>';$('startToday').onclick=()=>{document.querySelector(`[data-day-index="${info.index}"]`)?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.querySelector(`[data-day-index="${info.index}"] .exercise-card`)?.focus?.(),350);haptic()};$('todayWeek').onclick=()=>{document.querySelector('.week-grid')?.scrollIntoView({behavior:'smooth',block:'center'})}}
function parseMetric(v){if(v==null)return null;const m=String(v).replace(',','.').match(/\d+(?:\.\d+)?/);return m?Number(m[0]):null}
function exerciseHistory(){const rows={};WEEKS.forEach(w=>(PROGRAM[w.id]?.days||[]).forEach((d,di)=>d.exercises.forEach((ex,ei)=>{const log=logs[logKey(w.id,di,ei)];if(!log?.sets?.length)return;const nums=log.sets.map(parseMetric).filter(Number.isFinite);if(!nums.length)return;const value=Math.max(...nums);if(!rows[ex.key]||value>rows[ex.key].value)rows[ex.key]={name:ex.name,value,week:w.id,reps:ex.reps}})));return Object.values(rows).sort((a,b)=>b.value-a.value).slice(0,8)}
function consistency(){const weeks=12;const required=weeks*3;let doneDays=0;WEEKS.forEach(w=>(PROGRAM[w.id]?.days||[]).forEach((d,di)=>{if(d.exercises.length&&d.exercises.every((_,ei)=>isComplete(di,ei)))doneDays++}));return Math.round(doneDays/required*100)}
function qualityStats(){let clean=0,med=0,bad=0,completed=0;WEEKS.forEach(w=>(PROGRAM[w.id]?.days||[]).forEach((d,di)=>d.exercises.forEach((_,ei)=>{if(!isComplete(di,ei))return;completed++;const f=logs[logKey(w.id,di,ei)]?.feel;if(f==='clean')clean++;else if(f==='mediocre')med++;else if(f==='bad')bad++})));return {clean,med,bad,completed}}
function machineScore(){const qs=qualityStats(), total=totalExercises();const completion=total?qs.completed/total:0;const quality=qs.completed?(qs.clean+qs.med*.8+qs.bad*.6)/qs.completed:0;const consistencyScore=consistency()/100;const weekScore=completedWeeks()/12;return Math.round((completion*.4+quality*.35+consistencyScore*.15+weekScore*.1)*100)}
function achievements(){const qs=qualityStats(),cons=consistency();return[
['⚙️','FIRST REP','Complete your first exercise.',qs.completed>=1],['🔥','NO EXCUSES','Complete 10 exercises.',qs.completed>=10],['🟢','CLEAN MACHINE','Complete 10 exercises as CLEAN.',qs.clean>=10],['🏁','IRON WEEK','Complete every exercise in a Week.',completedWeeks()>=1],['📈','HALFWAY','Complete 6 full Weeks.',completedWeeks()>=6],['💎','PERFECT WEEK','Finish a Week with every exercise rated CLEAN.',WEEKS.some(w=>weekComplete(w.id)&&w.days.every((d,di)=>d.exercises.every((_,ei)=>logs[logKey(w.id,di,ei)]?.feel==='clean')))],['⚡','CONSISTENT','Reach 50% training-day consistency.',cons>=50],['👑','LEGEND','Complete Week 12.',weekComplete(12)]]}
function renderProgressFeatures(){const prs=exerciseHistory();$('prCount').textContent=prs.length;$('prList').innerHTML=prs.length?prs.map(x=>`<div class="pr-row"><span class="pr-name">${escapeHTML(x.name)}</span><span class="pr-value">${x.value} BEST · W${x.week}</span></div>`).join(''):'<p class="feature-note">Log actual set performance in your workouts and your bests will appear here.</p>';const ach=achievements(),unlocked=ach.filter(x=>x[3]).length;$('achievementCount').textContent=unlocked+' / '+ach.length;$('achievementList').innerHTML=ach.map(x=>`<div class="achievement ${x[3]?'unlocked':''}"><div class="achievement-icon">${x[3]?x[0]:'○'}</div><div class="achievement-name">${x[1]}</div><div class="achievement-note">${x[2]}</div></div>`).join('');const c=consistency();$('consistencyText').textContent=c+'%';$('consistencyFill').style.width=c+'%';$('consistencyNote').textContent=c>=80?'Strong consistency. Keep the standard.':c>=50?'Good base. Protect your Tuesday, Thursday and Friday sessions.':'Build the habit first: Tuesday, Thursday and Friday are your training days.';const hero=$('progressView');let ms=hero.querySelector('.machine-score');if(!ms){ms=document.createElement('section');ms.className='machine-score';hero.insertBefore(ms,hero.querySelector('.chart-card'))}ms.innerHTML=`<div class="feature-heading"><span>MACHINE SCORE</span><span>EXECUTION + CONSISTENCY</span></div><strong>${machineScore()}</strong><p class="feature-note">A transparent score from completion, performance quality, training-day consistency and completed Weeks.</p>`}
function startRest(seconds=90){restSeconds=Math.max(0,seconds);clearInterval(restTimer);$('restBar').classList.remove('hidden');renderRest();restTimer=setInterval(()=>{restSeconds--;renderRest();if(restSeconds<=0){clearInterval(restTimer);haptic([40,60,40]);setTimeout(()=>$('restBar').classList.add('hidden'),1200)}},1000)}
function renderRest(){const m=Math.floor(restSeconds/60),s=restSeconds%60;$('restTime').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function renderAll(){renderHero();renderWeeks();renderBanner();renderWorkouts();renderToday();renderProgressFeatures();}
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function resetWeekData(w){Object.keys(completions).filter(k=>k.startsWith(`w${w}:`)).forEach(k=>delete completions[k]);Object.keys(logs).filter(k=>k.startsWith(`${w}|`)).forEach(k=>delete logs[k]);persist()}
function openReset(kind){const w=week;$('resetTitle').textContent=kind==='all'?'RESET ALL TRAINING':'RESET WEEK '+w;$('resetText').textContent=kind==='all'?'All 12 weeks, exercise completions, set logs and training progress will be erased.':'All Training progress for Week '+w+' will be erased.';$('resetSheet').classList.remove('hidden');$('confirmReset').dataset.kind=kind}
function closeSettingsModal(){const sheet=$('settingsSheet');if(sheet.classList.contains('hidden'))return;sheet.classList.add('closing');setTimeout(()=>{sheet.classList.add('hidden');sheet.classList.remove('closing')},240)}
function closeSheets(){$('resetSheet').classList.add('hidden');$('settingsSheet').classList.add('hidden');$('settingsSheet').classList.remove('closing')}
$('settingsBtn').onclick=()=>{$('settingsSheet').classList.remove('hidden','closing')};$('closeSettings').onclick=closeSettingsModal;$('cancelReset').onclick=closeSheets;$('resetCurrent').onclick=()=>{closeSheets();setTimeout(()=>openReset('week'),120)};$('resetAll').onclick=()=>{closeSheets();setTimeout(()=>openReset('all'),120)};$('confirmReset').onclick=()=>{const kind=$('confirmReset').dataset.kind;if(kind==='all'){completions={};logs={};localStorage.removeItem(WEEK_KEY)}else resetWeekData(week);safeWrite(EX_KEY,completions);safeWrite(LOG_KEY,logs);closeSheets();haptic();renderAll();window.BTM_PROGRESS?.refresh?.()};$('resetSheet').addEventListener('click',e=>{if(e.target===$('resetSheet'))closeSheets()});$('settingsSheet').addEventListener('click',e=>{if(e.target===$('settingsSheet'))closeSettingsModal()});$('restPlus').onclick=()=>{restSeconds+=30;renderRest();haptic()};$('restSkip').onclick=()=>{restSeconds=0;clearInterval(restTimer);$('restBar').classList.add('hidden');haptic()};
$('trainingNav').onclick=()=>{window.BTM_PROGRESS?.show?.('training')||null;document.querySelector('#trainingView').classList.remove('hidden');document.querySelector('#progressView').classList.add('hidden');document.querySelector('.header-row h1').textContent='TRAINING'};$('progressNav').onclick=()=>{window.BTM_PROGRESS?.show?.('progress')||null;setTimeout(renderProgressFeatures,20)};
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
renderAll();
})();
