(()=>{
'use strict';
const SCHEDULE=[2,4,6];
const MESSAGES={0:['RECOVERY DAY.','Rest today. Come back stronger next week.'],1:['RECOVERY DAY.','Rest today. Come back stronger tomorrow.'],2:['TRAINING DAY.','Time to build.'],3:['RECOVERY DAY.','Rest today. Come back stronger tomorrow.'],4:['TRAINING DAY.','Get to work.'],5:['RECOVERY DAY.','Rest today. Come back stronger tomorrow.'],6:['TRAINING DAY.','Finish the week strong.']};
let lastDay=-1,lastMinute=-1;
function clock(){const now=new Date(),day=now.getDay(),hh=String(now.getHours()).padStart(2,'0'),mm=String(now.getMinutes()).padStart(2,'0'),dd=String(now.getDate()).padStart(2,'0'),month=now.toLocaleString('en-US',{month:'short'}).toUpperCase(),yyyy=now.getFullYear();let c=document.getElementById('btmLiveClock');if(!c){const header=document.querySelector('.header-row');if(!header)return;c=document.createElement('span');c.id='btmLiveClock';c.setAttribute('aria-label','Current local date and time');c.style.cssText='margin-left:auto;margin-right:8px;color:var(--muted);font:800 10px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;white-space:nowrap;align-self:center';header.insertBefore(c,document.getElementById('settingsBtn'))}c.textContent=`${dd} ${month} ${yyyy} • ${hh}:${mm}`;if(day!==lastDay||mm!==lastMinute){lastDay=day;lastMinute=mm;updateToday(day)}}
function updateToday(day){const box=document.getElementById('todayCard');if(!box)return;const text=MESSAGES[day]||MESSAGES[0],training=SCHEDULE.includes(day),labels=['TUESDAY','THURSDAY','SATURDAY'],index=SCHEDULE.indexOf(day),action=box.querySelector('#startToday');box.className=`today-card section-block ${training?'ready':'rest'}`;const title=box.querySelector('.today-title'),sub=box.querySelector('.today-sub'),kicker=box.querySelector('.today-kicker');if(kicker)kicker.textContent='TODAY';if(title)title.textContent=text[0];if(sub)sub.textContent=text[1];if(action){action.textContent=training?`START ${labels[index]} WORKOUT`:'';action.style.display=training?'':'none'}const weekBtn=box.querySelector('#todayWeek');if(weekBtn)weekBtn.style.display=training?'':'none'}
function boot(){clock();setInterval(clock,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
