(()=>{
'use strict';
const EX_KEY='btm_training_exercise_completion_v2';
const LOG_KEY='btm_progress';
const DAY_KEY='btm_training_current_day_v1';
const WEEK_KEY='btm_training_current_week_v1';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
function progressCalc(){const completions=read(EX_KEY,{}),logs=read(LOG_KEY,{}),program=window.BTM_TRAINING_WEEKS||{};let days=0,completedDays=0,done=0,clean=0,med=0,bad=0,total=0,fullWeeks=0;Object.values(program).forEach(w=>{let weekDone=true;(w.days||[]).forEach((d,di)=>{if(!d.exercises.length)return;days++;let dayDone=true;d.exercises.forEach((ex,ei)=>{total++;const k=`w${w.id}:d${di}:e${ei}`,lk=`${w.id}|${di}|${ei}`;if(completions[k]){done++;const f=logs[lk]?.feel;if(f==='clean')clean++;else if(f==='mediocre')med++;else if(f==='bad')bad++}else dayDone=false});if(dayDone)completedDays++;if(!dayDone)weekDone=false});if(weekDone)fullWeeks++});const consistency=days?Math.round(completedDays/days*100):0;const completion=total?done/total:0;const quality=done?(clean+med*.8+bad*.6)/done:0;const score=Math.round((completion*.4+quality*.35+(consistency/100)*.15+(fullWeeks/12)*.1)*100);return {consistency,score}}
function applyProgress(){const c=progressCalc();const t=document.getElementById('consistencyText'),f=document.getElementById('consistencyFill'),ms=document.querySelector('.machine-score strong');if(t)t.textContent=c.consistency+'%';if(f)f.style.width=c.consistency+'%';if(ms)ms.textContent=c.score}
function haptic(){if('vibrate' in navigator){try{navigator.vibrate(8)}catch{}}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getDay(){const v=Number(localStorage.getItem(DAY_KEY));return Number.isInteger(v)&&v>=0&&v<3?v:-1}
let selectedDay=getDay();
function saveDay(){if(selectedDay<0)localStorage.removeItem(DAY_KEY);else localStorage.setItem(DAY_KEY,String(selectedDay))}
function getDays(){return [...document.querySelectorAll('#workouts > .day')].map((el,index)=>({el,index,name:el.querySelector('.day-head strong')?.textContent?.trim()||`TRAINING DAY ${index+1}`,summary:el.querySelector('.day-head span')?.textContent?.trim()||''}))}
function injectStyles(){if(document.getElementById('btmDayStyles'))return;const s=document.createElement('style');s.id='btmDayStyles';s.textContent='.day-selector{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:0 0 14px}.day-select-card{min-height:92px;text-align:left;border:1px solid #203845;border-radius:16px;background:linear-gradient(145deg,#0c171e,#081118);color:#edf7fb;padding:13px;transition:transform .15s ease,border-color .15s ease,background .15s ease,box-shadow .15s ease}.day-select-card:active{transform:scale(.97)}.day-select-card.active{border-color:#66b9df;background:linear-gradient(145deg,rgba(102,185,223,.12),#081118);box-shadow:0 0 0 1px rgba(102,185,223,.18),0 10px 24px rgba(0,0,0,.18)}.day-select-card.complete{border-color:rgba(91,190,116,.55);background:linear-gradient(145deg,rgba(91,190,116,.14),#0a1713)}.day-select-name,.day-select-focus,.day-select-status{display:block}.day-select-name{font:800 14px ui-monospace,SFMono-Regular,Menlo,monospace}.day-select-focus{margin-top:5px;font-size:10px;color:#8298a5;line-height:1.25}.day-select-status{margin-top:10px;font:700 8px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.06em;color:#708693}.day-select-card.complete .day-select-status{color:#8ee19b}.day-hidden{display:none!important}.day-selected{animation:btmDayIn .18s ease}.workout-banner.day-prompt{min-height:72px;display:flex;align-items:center}.workout-banner.day-prompt>*{display:none}.workout-banner.day-prompt:after{content:"SELECT TUESDAY, THURSDAY OR FRIDAY TO START";font:800 11px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.09em;color:#8298a5}@keyframes btmDayIn{from{opacity:.55;transform:translateY(5px)}to{opacity:1;transform:none}}@media(max-width:520px){.day-selector{grid-template-columns:1fr;gap:8px}.day-select-card{min-height:70px;display:grid;grid-template-columns:1fr auto;grid-template-rows:auto auto;column-gap:12px;align-items:center}.day-select-name{grid-row:1/3}.day-select-focus{margin-top:0;text-align:right}.day-select-status{margin-top:2px;text-align:right}}';document.head.appendChild(s)}
function renderDaySelector(){const section=document.getElementById('workoutSection'),workouts=document.getElementById('workouts');if(!section||!workouts)return;let root=document.getElementById('daySelector');if(!root){root=document.createElement('div');root.id='daySelector';root.className='day-selector';section.insertBefore(root,document.getElementById('workoutBanner'))}const days=getDays();root.replaceChildren();days.forEach(({index,name,summary})=>{const b=document.createElement('button');b.type='button';b.className='day-select-card'+(selectedDay===index?' active':'');const m=summary.match(/^(\d+)\s*\/\s*(\d+)/);const complete=!!m&&Number(m[1])===Number(m[2]);if(complete)b.classList.add('complete');b.dataset.dayIndex=index;b.innerHTML=`<span class="day-select-name">${esc(name.split(' · ')[0])}</span><span class="day-select-focus">${esc(name.split(' · ')[1]||'TRAINING')}</span><span class="day-select-status">${complete?'✓ COMPLETE':esc(summary)}</span>`;b.onclick=()=>{selectedDay=index;saveDay();haptic();applyDayView();setTimeout(()=>document.querySelector(`#workouts > .day[data-day-index="${index}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}),40)};root.appendChild(b)})}
function applyDayView(){const days=getDays();days.forEach(({el,index})=>{el.classList.toggle('day-hidden',selectedDay!==index);el.classList.toggle('day-selected',selectedDay===index)});const banner=document.getElementById('workoutBanner');if(banner){banner.classList.toggle('day-prompt',selectedDay<0);if(selectedDay<0)banner.dataset.dayPrompt='true';else delete banner.dataset.dayPrompt}const w=Number(localStorage.getItem(WEEK_KEY))||1;const rank=(document.getElementById('currentRank')?.textContent||'').trim();const label=document.getElementById('selectedWeekLabel');if(label)label.textContent=selectedDay<0?`WEEK ${w} · ${rank}`:`WEEK ${w} · ${rank} · ${days[selectedDay]?.name?.split(' · ')[0]||''}`;const status=document.getElementById('selectedWeekStatus');if(status){const all=days.length===3&&days.every(({summary})=>{const m=summary.match(/^(\d+)\s*\/\s*(\d+)/);return m&&Number(m[1])===Number(m[2])});status.textContent=all?'COMPLETED':selectedDay<0?'SELECT A TRAINING DAY':'IN PROGRESS'}}
function rebuildDayUI(){injectStyles();renderDaySelector();applyDayView()}
function init(){rebuildDayUI();const grid=document.getElementById('weekGrid');if(grid)grid.addEventListener('click',()=>setTimeout(()=>{selectedDay=-1;saveDay();rebuildDayUI()},0));const today=document.getElementById('todayCard');if(today)today.addEventListener('click',e=>{if(!e.target.closest('#startToday'))return;const title=document.querySelector('#todayCard .today-title')?.textContent?.trim()||'';const idx=['TUESDAY','THURSDAY','FRIDAY'].findIndex(x=>title.toUpperCase().includes(x));if(idx>=0){selectedDay=idx;saveDay();setTimeout(rebuildDayUI,0)}});const workouts=document.getElementById('workouts');if(workouts)new MutationObserver(()=>rebuildDayUI()).observe(workouts,{childList:true,subtree:true});applyProgress()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setInterval(applyProgress,600);
})();
