(()=>{
'use strict';
if(window.__BTM_INTERACTION_POLISH__)return;
window.__BTM_INTERACTION_POLISH__=true;
const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)');
const style=document.createElement('style');
style.id='btmInteractionPolish';
style.textContent=`html{-webkit-tap-highlight-color:transparent;overscroll-behavior-x:none}body{overscroll-behavior-x:none}button,[role="button"],a,input,select,textarea{touch-action:manipulation}button,[role="button"]{transition:transform .14s cubic-bezier(.2,.75,.25,1),filter .14s ease,box-shadow .18s ease,background-color .18s ease,border-color .18s ease,color .18s ease;will-change:transform}button:active,[role="button"]:active{transform:scale(.98)}button:focus-visible,[role="button"]:focus-visible{outline:2px solid color-mix(in srgb,var(--blue,#66b9df) 70%,transparent);outline-offset:2px}.btm-pressing{transform:scale(.98)!important;filter:brightness(1.035)}.btm-ripple-host{position:relative;overflow:hidden}.btm-ripple{position:absolute;width:18px;height:18px;border-radius:50%;pointer-events:none;background:rgba(185,231,249,.18);transform:translate(-50%,-50%) scale(0);animation:btmRipple .38s cubic-bezier(.2,.7,.25,1) forwards}@keyframes btmRipple{0%{opacity:.55;transform:translate(-50%,-50%) scale(0)}100%{opacity:0;transform:translate(-50%,-50%) scale(5.5)}}#app{touch-action:pan-y}#workouts,#progressView{touch-action:pan-y;-webkit-overflow-scrolling:touch}.sheet-backdrop{overscroll-behavior:contain}.sheet{transform:translateZ(0);backface-visibility:hidden}.title-section,.achievement-card,.week-card,.day-head,.exercise-card,.feature-panel,.stat,.chart-card{backface-visibility:hidden;transform:translateZ(0)}.title-equipped{transition:opacity .18s ease,transform .18s cubic-bezier(.2,.75,.25,1),text-shadow .18s ease}.title-equipped-logo{transition:transform .18s cubic-bezier(.2,.75,.25,1),opacity .18s ease}.title-select-trigger,.title-choice,.achievement-claim,.sheet-button,.secondary,.danger,.icon-btn,.nav-btn,.today-action,.complete-btn,.feel-btn,.week-card,.day-head{user-select:none;-webkit-user-select:none}.title-select-trigger:active,.title-choice:active,.achievement-claim:active,.sheet-button:active,.secondary:active,.danger:active,.icon-btn:active,.nav-btn:active,.today-action:active,.complete-btn:active,.feel-btn:active,.week-card:active,.day-head:active{transform:scale(.975)}@media (hover:hover) and (pointer:fine){button:hover,[role="button"]:hover{filter:brightness(1.025)}.week-card:hover,.day-head:hover,.exercise-card:hover,.achievement-card:hover,.feature-panel:hover{transform:translateY(-1px)}}@media (prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important}button,[role="button"]{will-change:auto}.btm-ripple{display:none}}`;
document.head.appendChild(style);
function isInteractive(el){return el?.closest?.('button,[role="button"],a,.title-choice,.title-select-trigger,.feel-btn,.complete-btn,.week-card,.day-head');}
function ripple(e,target){if(reduced?.matches)return;if(!target.classList.contains('btm-ripple-host'))target.classList.add('btm-ripple-host');const r=document.createElement('span');r.className='btm-ripple';const rect=target.getBoundingClientRect();r.style.left=`${e.clientX-rect.left}px`;r.style.top=`${e.clientY-rect.top}px`;target.appendChild(r);setTimeout(()=>r.remove(),420)}
function press(e){const t=isInteractive(e.target);if(!t||e.pointerType==='mouse'&&e.buttons!==1)return;t.classList.add('btm-pressing');if(e.pointerType!=='mouse')ripple(e,t)}
function release(e){const t=isInteractive(e.target);if(t)t.classList.remove('btm-pressing')}
document.addEventListener('pointerdown',press,{passive:true});document.addEventListener('pointerup',release,{passive:true});document.addEventListener('pointercancel',release,{passive:true});document.addEventListener('pointerleave',release,{passive:true});
// Use device feedback only where the platform/browser exposes it. iOS Safari normally does not, so nothing is faked.
document.addEventListener('click',e=>{const t=isInteractive(e.target);if(!t||!navigator.vibrate)return;const important=t.matches('.complete-btn,.achievement-claim,.title-choice,#closeSettings,#confirmReset,.danger')||t.id==='themeToggle';if(important){try{navigator.vibrate(t.matches('.achievement-claim,.confirmReset,.danger')?[10,24,10]:8)}catch{}}},{passive:true});
// Prevent accidental double activation without disabling legitimate rapid controls.
let lastTarget=null,lastTime=0;document.addEventListener('dblclick',e=>{const t=isInteractive(e.target);if(!t)return;if(t.matches('.complete-btn,.achievement-claim,.title-choice')){e.preventDefault();}},true);
})();
