(()=>{
'use strict';
const WEEKS=window.BTM_WEEKS||[];
const PROGRAM=window.BTM_TRAINING_WEEKS||{};
const EX_KEY='btm_training_exercise_completion_v2';
const LOG_KEY='btm_progress';
const WEEK_KEY='btm_training_current_week_v1';
const THEME_KEY='btm_theme_v1';
const QUALITY=Object.freeze({clean:1,mediocre:.8,bad:.6});
const clamp=n=>Math.max(0,Math.min(100,Number.isFinite(n)?n:0));
const pct=ratio=>Math.round(clamp(ratio*100));
const $=id=>document.getElementById(id);
const read=(key,f)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??f}catch{return f}};
let state={completions:{},logs:{}};
let activeScreen='training';
let dataSignature='';
function data(){return {completions:read(EX_KEY,{}),logs:read(LOG_KEY,{})}}
function key(w,d,e){return `w${w}:d${d}:e${e}`}
function logKey(w,d,e){return `${w}|${d}|${e}`}
function weekInfo(w){const days=(PROGRAM[w]||{}).days||[];let total=0,completed=0,score=0,clean=0,mediocre=0,bad=0;days.forEach((day,d)=>day.exercises.forEach((ex,e)=>{total++;const done=!!state.completions[key(w,d,e)];const log=state.logs[logKey(w,d,e)]||{};if(done){completed++;const q=QUALITY[log.feel]||0;score+=q;if(log.feel==='clean')clean++;if(log.feel==='mediocre')mediocre++;if(log.feel==='bad')bad++}}));return {w,total,completed,score:pct(total?score/total:0),clean,mediocre,bad,completionRate:pct(total?completed/total:0),tracked:completed>0}}
function calc(){state=data();const weeks=WEEKS.map(w=>weekInfo(w.id));const tracked=weeks.filter(x=>x.tracked);const totalExercises=weeks.reduce((s,x)=>s+x.total,0);const completedExercises=weeks.reduce((s,x)=>s+x.completed,0);const overall=pct(totalExercises?completedExercises/totalExercises:0);const latest=tracked.at(-1)||null;const previous=tracked.length>1?tracked[tracked.length-2]:null;const best=tracked.length?tracked.reduce((a,b)=>b.score>a.score?b:a):null;const counts=weeks.reduce((a,x)=>{a.clean+=x.clean;a.mediocre+=x.mediocre;a.bad+=x.bad;return a},{clean:0,mediocre:0,bad:0});const trend=latest&&previous?clamp(latest.score-previous.score):0;return {weeks,tracked,overall,totalExercises,completedExercises,best,completionRate:overall,...counts,trend}}
function chartPath(items){const points=items.map(x=>({x:42+(x.w-1)*(516/11),y:220-(x.score*1.82)}));if(!points.length)return {line:'',area:'',points:[]};const line=points.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' ');return {line,area:line+' L '+points.at(-1).x.toFixed(1)+' 220 L '+points[0].x.toFixed(1)+' 220 Z',points}}
function renderChart(c){const svg=$('progressChart');if(!svg)return;const rows=[0,25,50,75,100];const grid=rows.map(v=>{const y=220-v*1.82;return `<line x1="42" y1="${y}" x2="558" y2="${y}" class="chart-grid"/><text x="4" y="${y+4}" class="chart-y">${v}%</text>`}).join('');const ticks=Array.from({length:12},(_,i)=>{const x=42+i*(516/11);return `<line x1="${x}" y1="220" x2="${x}" y2="224" class="chart-tick"/>`}).join('');const {line,area,points}=chartPath(c.weeks.filter(x=>x.tracked));svg.innerHTML=`<defs><linearGradient id="progressArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-opacity=".28"/><stop offset="100%" stop-opacity="0"/></linearGradient></defs><rect x="42" y="38" width="516" height="182" class="chart-bg"/>${grid}${ticks}<line x1="42" y1="220" x2="558" y2="220" class="chart-axis"/>${area?`<path d="${area}" class="chart-area"/>`:''}${line?`<path d="${line}" class="chart-line"/>`:''}${points.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="4" class="chart-point"/>`).join('')}`;$('chartLabels').innerHTML=Array.from({length:12},(_,i)=>`<span>W${i+1}</span>`).join('')}
function renderWeekly(c){$('weeklyTracked').textContent=c.tracked.length+' TRACKED';$('weeklyScores').innerHTML=c.weeks.map(x=>`<button type="button" class="weekly-row ${x.tracked?'tracked':'untracked'}" data-week="${x.w}"><span class="weekly-name">WEEK ${x.w}${x.w===7?' · DELOAD':''}</span><span class="weekly-score">${x.tracked?x.score+'%':'—'}</span></button>`).join('');document.querySelectorAll('.weekly-row').forEach(b=>b.onclick=()=>{localStorage.setItem(WEEK_KEY,String(Number(b.dataset.week)));show('training');$('workoutSection')?.scrollIntoView({behavior:'smooth',block:'start'})})}
function render(){const c=calc();dataSignature=JSON.stringify(state);renderChart(c);renderWeekly(c);$('progressOverall').textContent=c.overall+'%';$('progressOverallFill').style.width=c.overall+'%';$('progressTracked').textContent=c.completedExercises+' / '+c.totalExercises+' EXERCISES';$('statCurrent').textContent='WEEK '+(Number(localStorage.getItem(WEEK_KEY))||1);$('statBest').textContent=c.best?`WEEK ${c.best.w} · ${c.best.score}%`:'—';$('statAverage').textContent=c.tracked.length?Math.round(c.tracked.reduce((s,x)=>s+x.score,0)/c.tracked.length)+'%':'—';$('statTrend').textContent=(c.trend>0?'+':'')+c.trend+'% '+(c.trend>0?'↑':c.trend<0?'↓':'→');$('statClean').textContent=c.clean;$('statMediocre').textContent=c.mediocre;$('statBad').textContent=c.bad;$('statCompletion').textContent=c.completionRate+'%';$('overallProgress').textContent=c.overall+'%';$('overallFill').style.width=c.overall+'%'}
function show(screen){activeScreen=screen;const training=screen==='training';$('trainingView').classList.toggle('hidden',!training);$('progressView').classList.toggle('hidden',training);$('trainingNav').classList.toggle('active',training);$('progressNav').classList.toggle('active',!training);document.querySelector('.header-row h1').textContent=training?'TRAINING':'PROGRESS';if(!training)render();window.scrollTo({top:0,behavior:'smooth'})}
function applyTheme(theme){const dark=theme==='dark';document.body.classList.toggle('dark-mode',dark);$('themeToggle').textContent='DARK MODE: '+(dark?'ON':'OFF');$('themeColorMeta').content=dark?'#030508':'#071016';localStorage.setItem(THEME_KEY,dark?'dark':'normal')}
function enhanceRatings(){document.querySelectorAll('.exercise-card').forEach(card=>{const complete=card.classList.contains('complete');const row=card.querySelector('.feel-row');if(!row)return;let label=card.querySelector('.performance-label');if(!label){label=document.createElement('div');label.className='performance-label';label.textContent='PERFORMANCE';row.parentNode.insertBefore(label,row)}row.querySelectorAll('.feel-btn').forEach(b=>{b.disabled=!complete;b.setAttribute('aria-disabled',String(!complete))});row.classList.toggle('rating-disabled',!complete)})}
function themeInit(){applyTheme(localStorage.getItem(THEME_KEY)||'normal')}
const observer=new MutationObserver(()=>{enhanceRatings()});observer.observe($('app'),{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
$('trainingNav').onclick=()=>show('training');$('progressNav').onclick=()=>show('progress');$('themeToggle').onclick=()=>applyTheme(document.body.classList.contains('dark-mode')?'normal':'dark');themeInit();enhanceRatings();
setInterval(()=>{const next=data();const sig=JSON.stringify(next);if(sig!==dataSignature){state=next;render()}else if(activeScreen==='progress'){render()}},700);
window.BTM_PROGRESS={refresh:render,show};
})();
