(()=>{
'use strict';
const E=window.BTM_PROGRESS_ENGINE;
if(!E){console.error('BTM progress engine missing');return}
const EX_KEY='btm_training_exercise_completion_v2',LOG_KEY='btm_progress',WEEK_KEY='btm_training_current_week_v1',THEME_KEY='btm_theme_v1';
const $=id=>document.getElementById(id),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
let activeScreen='training',dataSignature='';
function calc(){return E.calculateAll()}
function chartPath(items){const points=items.map(x=>({x:42+(x.week-1)*(516/11),y:220-(x.performance.percent*1.82)}));if(!points.length)return{line:'',area:'',points:[]};const line=points.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' ');return{line,area:line+' L '+points.at(-1).x.toFixed(1)+' 220 L '+points[0].x.toFixed(1)+' 220 Z',points}}
function renderChart(c){const svg=$('progressChart');if(!svg)return;const rows=[0,25,50,75,100];const grid=rows.map(v=>{const y=220-v*1.82;return `<line x1="42" y1="${y}" x2="558" y2="${y}" class="chart-grid"/><text x="4" y="${y+4}" class="chart-y">${v}%</text>`}).join('');const ticks=Array.from({length:12},(_,i)=>{const x=42+i*(516/11);return `<line x1="${x}" y1="220" x2="${x}" y2="224" class="chart-tick"/>`}).join('');const {line,area,points}=chartPath(c.weekMetrics.filter(x=>x.completedDays>0));svg.innerHTML=`<defs><linearGradient id="progressArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-opacity=".28"/><stop offset="100%" stop-opacity="0"/></linearGradient></defs><rect x="42" y="38" width="516" height="182" class="chart-bg"/>${grid}${ticks}<line x1="42" y1="220" x2="558" y2="220" class="chart-axis"/>${area?`<path d="${area}" class="chart-area"/>`:''}${line?`<path d="${line}" class="chart-line"/>`:''}${points.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="4" class="chart-point"/>`).join('')}`;if($('chartLabels'))$('chartLabels').innerHTML=Array.from({length:12},(_,i)=>`<span>W${i+1}</span>`).join('')}
function renderWeekly(c){const root=$('weeklyScores');if(!root)return;root.innerHTML=c.weekMetrics.map(x=>`<button type="button" class="weekly-row ${x.completedDays?'tracked':'untracked'}" data-week="${x.week}"><span class="weekly-name">WEEK ${x.week}${x.week===7?' · DELOAD':''}</span><span class="weekly-score">${x.completedDays?x.performance.percent+'%':'—'}</span></button>`).join('');root.querySelectorAll('.weekly-row').forEach(b=>b.onclick=()=>{localStorage.setItem(WEEK_KEY,String(Number(b.dataset.week)));show('training');$('workoutSection')?.scrollIntoView({behavior:'smooth',block:'start'})})}
function render(){const c=calc();dataSignature=JSON.stringify({completions:c.completions,logs:c.logs});renderChart(c);renderWeekly(c);if($('progressOverall'))$('progressOverall').textContent=c.overallProgramPercent+'%';if($('progressOverallFill'))$('progressOverallFill').style.width=c.overallProgramPercent+'%';if($('progressTracked'))$('progressTracked').textContent=c.totalTrainingDays?(c.completedTrainingDays+' / '+c.totalTrainingDays+' TRAINING DAYS'):'NO TRAINING DAYS YET';if($('statCurrent'))$('statCurrent').textContent='WEEK '+(Number(localStorage.getItem(WEEK_KEY))||1);const tracked=c.weekMetrics.filter(x=>x.completedDays>0),best=tracked.length?tracked.reduce((a,b)=>b.performance.percent>a.performance.percent?b:a):null,latest=tracked.at(-1),previous=tracked.length>1?tracked.at(-2):null,trend=latest&&previous?latest.performance.percent-previous.performance.percent:0;if($('statBest'))$('statBest').textContent=best?`WEEK ${best.week} · ${best.performance.percent}%`:'—';if($('statAverage'))$('statAverage').textContent=c.averagePerformancePercent+'%';if($('statTrend'))$('statTrend').textContent=(trend>0?'+':'')+trend+'% '+(trend>0?'↑':trend<0?'↓':'→');if($('statClean'))$('statClean').textContent=c.clean;if($('statMediocre'))$('statMediocre').textContent=c.mediocre;if($('statBad'))$('statBad').textContent=c.bad;if($('statCompletion'))$('statCompletion').textContent=c.overallProgramPercent+'%'}
function show(screen){activeScreen=screen;const training=screen==='training';$('trainingView')?.classList.toggle('hidden',!training);$('progressView')?.classList.toggle('hidden',training);$('trainingNav')?.classList.toggle('active',training);$('progressNav')?.classList.toggle('active',!training);const h=document.querySelector('.header-row h1');if(h)h.textContent=training?'TRAINING':'PROGRESS';if(!training)render();window.scrollTo({top:0,behavior:'smooth'})}
function applyTheme(theme){const dark=theme==='dark';document.body.classList.toggle('dark-mode',dark);if($('themeToggle'))$('themeToggle').textContent='DARK MODE: '+(dark?'ON':'OFF');if($('themeColorMeta'))$('themeColorMeta').content=dark?'#030508':'#071016';localStorage.setItem(THEME_KEY,dark?'dark':'normal')}
function enhanceRatings(){document.querySelectorAll('.exercise-card').forEach(card=>{const complete=card.classList.contains('complete'),row=card.querySelector('.feel-row');if(!row)return;let label=card.querySelector('.performance-label');if(!label){label=document.createElement('div');label.className='performance-label';label.textContent='PERFORMANCE';row.parentNode.insertBefore(label,row)}row.querySelectorAll('.feel-btn').forEach(b=>{b.disabled=!complete;b.setAttribute('aria-disabled',String(!complete))});row.classList.toggle('rating-disabled',!complete)})}
function themeInit(){applyTheme(localStorage.getItem(THEME_KEY)||'normal')}
$('trainingNav')?.addEventListener('click',()=>show('training'));$('progressNav')?.addEventListener('click',()=>show('progress'));$('themeToggle')?.addEventListener('click',()=>applyTheme(document.body.classList.contains('dark-mode')?'normal':'dark'));themeInit();enhanceRatings();
setInterval(()=>{const next=E.calculateAll(),sig=JSON.stringify({completions:next.completions,logs:next.logs});if(sig!==dataSignature){dataSignature=sig;if(activeScreen==='progress')render();enhanceRatings()}else if(activeScreen==='progress'){render()}},700);
window.BTM_PROGRESS={refresh:render,show};
})();
