(()=>{
'use strict';
const SKIP_KEY='btm_training_skipped_days_v1',EX_KEY='btm_training_exercise_completion_v2',LOG_KEY='btm_progress',WEEK_KEY='btm_training_current_week_v1';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const WEEKS=window.BTM_WEEKS||[],PROGRAM=window.BTM_TRAINING_WEEKS||{};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const exKey=(w,d,e)=>`w${w}:d${d}:e${e}`;
const logKey=(w,d,e)=>`${w}|${d}|${e}`;
const currentWeek=()=>Number(localStorage.getItem(WEEK_KEY))||1;
const skipped=()=>{const x=read(SKIP_KEY,{});return x&&typeof x==='object'?x:{}};
const dayKey=(w,d)=>`${w}|${d}`;
const isSkipped=(w,d)=>!!skipped()[dayKey(w,d)];
const dayProgram=(w,d)=>PROGRAM[w]?.days?.[d]||null;
const dayComplete=(w,d)=>{const p=dayProgram(w,d);const c=read(EX_KEY,{});return !!p?.exercises?.length&&p.exercises.every((_,e)=>!!c[exKey(w,d,e)])};
function haptic(p=8){try{navigator.vibrate?.(p)}catch{}}
function persistSkip(w,d,value){const s=skipped();if(value)s[dayKey(w,d)]={skippedAt:new Date().toISOString()};else delete s[dayKey(w,d)];write(SKIP_KEY,s);haptic();}
function clearCurrentDayData(w,d){const c=read(EX_KEY,{}),l=read(LOG_KEY,{});const p=dayProgram(w,d);if(p?.exercises)p.exercises.forEach((_,e)=>{delete c[exKey(w,d,e)];delete l[logKey(w,d,e)]});write(EX_KEY,c);write(LOG_KEY,l)}
function orderedSlot(w,d){return (w-1)*3+d}
function consecutiveMissesBefore(w,d){let count=0;let slot=orderedSlot(w,d)-1;while(slot>=0){const pw=Math.floor(slot/3)+1,pd=slot%3;if(!isSkipped(pw,pd))break;count++;slot--}return count}
function previousPrescription(w,d,e,misses){if(!misses)return null;let back=Math.min(misses,2),target=w-back;while(target>=1){const source=dayProgram(target,d)?.exercises?.[e];if(source&&!WEEKS.find(x=>x.id===target)?.isDeload)return source;target--}return null}
function effectiveExercise(w,d,e,source){const misses=consecutiveMissesBefore(w,d);if(!misses)return {exercise:source,misses:0,adjusted:false};const previous=previousPrescription(w,d,e,misses);return {exercise:previous||source,misses,adjusted:!!previous}}
function ensureModal(){let root=document.getElementById('skipConfirm');if(root)return root;root=document.createElement('div');root.id='skipConfirm';root.className='skip-confirm-backdrop hidden';root.innerHTML='<div class="skip-confirm" role="dialog" aria-modal="true" aria-labelledby="skipConfirmTitle"><h2 id="skipConfirmTitle"></h2><p id="skipConfirmText"></p><div class="skip-confirm-actions"><button type="button" class="skip-cancel" id="skipCancel">CANCEL</button><button type="button" class="skip-confirm-action" id="skipConfirmAction"></button></div></div>';document.body.appendChild(root);root.addEventListener('click',e=>{if(e.target===root)closeModal()});root.querySelector('#skipCancel').onclick=closeModal;return root}
function closeModal(){document.getElementById('skipConfirm')?.classList.add('hidden')}
function openModal(w,d,undo=false){const root=ensureModal(),day=dayProgram(w,d),name=(day?.day||['TUESDAY','THURSDAY','SATURDAY'][d]).split(' · ')[0];root.querySelector('#skipConfirmTitle').textContent=undo?'UNDO SKIP?':'SKIP THIS WORKOUT?';root.querySelector('#skipConfirmText').textContent=undo?`Restore ${name} to NOT STARTED. The progression adjustment from this skip will be removed.`:'This session will be marked as skipped and your progression for the next session will be adjusted.';const action=root.querySelector('#skipConfirmAction');action.textContent=undo?'UNDO SKIP':'SKIP DAY';action.onclick=()=>{if(undo){persistSkip(w,d,false)}else{if(dayComplete(w,d))return;clearCurrentDayData(w,d);persistSkip(w,d,true)}closeModal();setTimeout(()=>{refreshAll();window.BTM_PROGRESS?.refresh?.();window.BTM_ACHIEVEMENTS?.refresh?.()},30)};root.classList.remove('hidden');haptic(6)}
function skippedCount(){return Object.keys(skipped()).length}
function addProgressSummary(){const progress=document.getElementById('progressView');if(!progress)return;let box=document.getElementById('skipSummary');if(!box){box=document.createElement('section');box.id='skipSummary';box.className='skip-summary';const weekly=progress.querySelector('.weekly-list');(weekly?weekly.before(box):progress.appendChild(box))}const count=skippedCount();box.innerHTML=`<div class="feature-heading"><span>SKIPPED SESSIONS</span><span>${count}</span></div><strong>${count}</strong><p class="feature-note">Skipped workouts do not count toward completion or consistency.</p>`}
function syncSkippedCards(dayEl,w,d,skip){const cards=[...dayEl.querySelectorAll('.exercise-card')],c=read(EX_KEY,{}),l=read(LOG_KEY,{});cards.forEach((card,e)=>{const done=!!c[exKey(w,d,e)];const button=card.querySelector('.complete-btn');card.classList.toggle('complete',skip?false:done);if(button){button.classList.toggle('done',skip?false:done);button.textContent=skip?'SKIPPED':done?'✓ COMPLETED':'COMPLETE';button.disabled=skip}card.querySelectorAll('.set-input,.exercise-note').forEach(x=>x.disabled=skip);card.querySelectorAll('.feel-btn').forEach(x=>x.disabled=skip?!0:!done);if(!skip){const log=l[logKey(w,d,e)]||{};card.querySelectorAll('.feel-btn').forEach((x,i)=>x.classList.toggle('active',['clean','mediocre','bad'][i]===log.feel))}})}
function decorateDay(dayEl,w,d){const p=dayProgram(w,d);if(!p)return;const skip=isSkipped(w,d),complete=dayComplete(w,d);dayEl.classList.toggle('skip-state',skip);dayEl.dataset.skipState=skip?'skipped':complete?'completed':'not-started';const head=dayEl.querySelector('.day-head');if(!head)return;let action=head.querySelector('.skip-day-action');if(!action){action=document.createElement('button');action.type='button';action.className='skip-day-action';head.appendChild(action)}action.disabled=false;action.style.opacity='1';if(skip){action.textContent='UNDO SKIP';action.onclick=()=>openModal(w,d,true)}else if(complete){action.textContent='COMPLETED';action.disabled=true;action.style.opacity='.45'}else{action.textContent='SKIP DAY';action.onclick=()=>openModal(w,d,false)}
let badge=dayEl.querySelector('.skip-badge');if(skip){if(!badge){badge=document.createElement('div');badge.className='skip-badge';dayEl.insertBefore(badge,dayEl.querySelector('.exercise-card')||null)}badge.textContent='SKIPPED · TRAINING STIMULUS MISSED'}else badge?.remove();
let note=dayEl.querySelector('.skip-adjustment');const misses=consecutiveMissesBefore(w,d);const hasAdjusted=misses>0&&!skip&&[...dayEl.querySelectorAll('.exercise-card')].some((_,e)=>effectiveExercise(w,d,e,p.exercises[e]).adjusted);if(hasAdjusted){if(!note){note=document.createElement('div');note.className='skip-adjustment';const badgeEl=dayEl.querySelector('.skip-badge');(badgeEl?badgeEl.after(note):head.after(note))}note.innerHTML=`<strong>PROGRESSION ADJUSTED</strong>${misses===1?'The previous training session was skipped, so today\'s progression is held at the previous appropriate level.':`${misses} consecutive sessions were skipped, so progression is temporarily held at an earlier appropriate level.`}`}else note?.remove();syncSkippedCards(dayEl,w,d,skip)}
function patchPrescription(card,w,d,e){const source=dayProgram(w,d)?.exercises?.[e];if(!source)return;const result=effectiveExercise(w,d,e,source);card.dataset.skipAdjusted=result.adjusted?'1':'0';if(!result.adjusted)return;const ex=result.exercise;const vals=card.querySelectorAll('.metric-value');if(vals[0])vals[0].textContent=`${ex.sets} × ${ex.reps}`;if(vals[1])vals[1].textContent=ex.rir;const grid=card.querySelector('.set-grid');if(grid&&grid.children.length!==ex.sets){const logs=read(LOG_KEY,{}),old=logs[logKey(w,d,e)]?.sets||[];grid.replaceChildren();for(let i=0;i<ex.sets;i++){const input=document.createElement('input');input.className='set-input';input.inputMode='decimal';input.placeholder='Set '+(i+1);input.value=old[i]||'';input.addEventListener('input',()=>{const next=read(LOG_KEY,{});const log=next[logKey(w,d,e)]||{done:false,feel:'',sets:[],note:''};log.sets[i]=input.value;next[logKey(w,d,e)]=log;write(LOG_KEY,next)});grid.appendChild(input)}}}
function refreshWorkouts(){const w=currentWeek();document.querySelectorAll('#workouts>.day').forEach((day,d)=>{decorateDay(day,w,d);day.querySelectorAll('.exercise-card').forEach((card,e)=>patchPrescription(card,w,d,e))})}
function refreshAll(){refreshWorkouts();addProgressSummary()}
function boot(){ensureModal();refreshAll();const workouts=document.getElementById('workouts');if(workouts){let timer=0;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(refreshWorkouts,25)}).observe(workouts,{childList:true,subtree:true})}const progress=document.getElementById('progressView');if(progress)new MutationObserver(()=>setTimeout(addProgressSummary,0)).observe(progress,{childList:true,subtree:true});document.getElementById('weekGrid')?.addEventListener('click',()=>setTimeout(refreshAll,50));setInterval(()=>{if(document.getElementById('workouts'))refreshAll()},1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,100));else setTimeout(boot,100);
window.BTM_SKIP={isSkipped,skippedCount,refresh:refreshAll};
})();